import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const blankProduct={name:"",code:"",category:"Espetos",description:"",image_url:"",cost:0,price:0,stock:0,min_stock:10,unit:"un",sector:"Churrasqueira",printer:"Nenhuma",track_stock:true,active:true};

function App(){
 const[session,setSession]=useState(null),[user,setUser]=useState("admin"),[pass,setPass]=useState("1234"),[page,setPage]=useState("dashboard"),[data,setData]=useState({}),[error,setError]=useState("");
 const api=async(path,opt={})=>{const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.token}`}:{})},...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||"Erro ao processar");return j};
 const load=async()=>{if(!session)return;const safe=async(path,fallback=[])=>{try{return await api(path)}catch(e){console.error(path,e);return fallback}};const n={products:await safe("/products"),tables:await safe("/tables"),production:await safe("/production"),printJobs:await safe("/print-jobs"),customers:await safe("/customers"),reservations:await safe("/reservations"),cash:await safe("/cash/status",{})};if(session.role==="admin"){n.dashboard=await safe("/dashboard",{});n.expenses=await safe("/expenses");n.audit=await safe("/audit")}setData(n)};
 useEffect(()=>{if(!session)return;load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[session]);
 const login=async()=>{try{setError("");const s=await api("/auth/login",{method:"POST",body:JSON.stringify({username:user,password:pass})});setSession(s);setPage(s.role==="admin"?"dashboard":"tables")}catch(e){setError(e.message)}};
 const request=async(path,opt={})=>{try{setError("");const out=await api(path,opt);await load();return out}catch(e){setError(e.message);throw e}};
 if(!session)return <div className="login"><div className="loginCard"><div className="logo">R</div><h1>REI'SPETOS OS</h1><p>Gestão operacional</p><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Usuário"/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Senha" onKeyDown={e=>e.key==="Enter"&&login()}/><button onClick={login}>Entrar</button>{error&&<div className="error">{error}</div>}<small>admin / 1234<br/>caixa / 0000</small></div></div>;
 const admin=session.role==="admin";const menu=admin?["dashboard","products","tables","waiter","production","cash","reports","customers","reservations","expenses","audit"]:["waiter","tables","production","cash","customers","reservations"];
 const names={dashboard:"Dashboard",products:"Produtos",tables:"Mesas e Comandas",waiter:"App Garçom",production:"Produção",cash:"Caixa",reports:"Relatórios",customers:"Clientes",reservations:"Reservas",expenses:"Despesas",audit:"Auditoria"};
 return <div className="app"><aside><div className="brand"><div className="mini">R</div><div><b>REI'SPETOS</b><span>{admin?"Admin / Dono":"Caixa"}</span></div></div><nav>{menu.map(m=><button key={m} className={page===m?"active":""} onClick={()=>setPage(m)}>{names[m]}</button>)}</nav><button className="danger" onClick={()=>setSession(null)}>Sair</button></aside><main><div className="pageHead"><div><h1>{names[page]}</h1><p>Sistema REI'SPETOS</p></div></div>{error&&<div className="error">{error}</div>}{page==="dashboard"&&admin&&<Dashboard d={data.dashboard}/>} {page==="products"&&admin&&<Products products={data.products||[]} request={request}/>} {page==="tables"&&<Tables tables={data.tables||[]} products={(data.products||[]).filter(x=>x.active)} request={request}/>} {page==="waiter"&&<WaiterApp tables={data.tables||[]} products={(data.products||[]).filter(x=>x.active)} request={request}/>} {page==="production"&&<Production items={data.production||[]} printJobs={data.printJobs||[]} request={request}/>} {page==="cash"&&<Cash data={data.cash||{}} request={request}/>} {page==="reports"&&admin&&<Reports request={request}/>} {page==="customers"&&<Customers items={data.customers||[]} request={request}/>} {page==="reservations"&&<Reservations items={data.reservations||[]} request={request}/>} {page==="expenses"&&admin&&<Expenses items={data.expenses||[]} request={request}/>} {page==="audit"&&admin&&<Audit items={data.audit||[]}/>}</main></div>
}

const Dashboard=({d})=>d?<><div className="cards"><div className="card"><span>Faturamento</span><b>{money(d.revenue)}</b></div><div className="card"><span>Lucro estimado</span><b>{money(d.profit)}</b></div><div className="card"><span>Mesas abertas</span><b>{d.open_tables}</b></div><div className="card"><span>Estoque crítico</span><b>{d.low_stock}</b></div></div><div className="panel welcome"><h2>Operação pronta</h2><p>Cadastre produtos com custo, margem, setor de produção e estoque mínimo. O próximo módulo será Mesas e Comandas individuais.</p></div></>:null;

function Products({products,request}){
 const[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blankProduct),[search,setSearch]=useState(""),[category,setCategory]=useState("Todos"),[stockModal,setStockModal]=useState(null),[stockForm,setStockForm]=useState({qty:0,movement_type:"entry",note:""});
 const cats=useMemo(()=>["Todos",...new Set(products.map(p=>p.category||"Outros"))],[products]);
 const shown=products.filter(p=>(category==="Todos"||(p.category||"Outros")===category)&&(`${p.name} ${p.code||""}`.toLowerCase().includes(search.toLowerCase())));
 const startNew=()=>{setEditing(null);setForm(blankProduct);setOpen(true)};
 const startEdit=p=>{setEditing(p);setForm({...blankProduct,...p});setOpen(true)};
 const save=async()=>{const opt={method:editing?"PUT":"POST",body:JSON.stringify({...form,cost:+form.cost,price:+form.price,stock:+form.stock,min_stock:+form.min_stock})};await request(editing?`/products/${editing.id}`:"/products",opt);setOpen(false)};
 const deactivate=async p=>{if(confirm(`Desativar ${p.name}?`))await request(`/products/${p.id}`,{method:"DELETE"})};
 const adjust=async()=>{await request(`/products/${stockModal.id}/stock`,{method:"POST",body:JSON.stringify({...stockForm,qty:+stockForm.qty})});setStockModal(null);setStockForm({qty:0,movement_type:"entry",note:""})};
 const active=products.filter(p=>p.active).length,critical=products.filter(p=>p.active&&p.track_stock&&p.stock<=p.min_stock).length,totalValue=products.reduce((s,p)=>s+(p.active?p.stock*p.cost:0),0);
 return <>
  <div className="cards productStats"><div className="card"><span>Produtos ativos</span><b>{active}</b></div><div className="card"><span>Estoque crítico</span><b>{critical}</b></div><div className="card"><span>Valor em estoque</span><b>{money(totalValue)}</b></div><div className="card actionCard"><button onClick={startNew}>+ Novo produto</button></div></div>
  <div className="toolbar"><input placeholder="Buscar produto ou código" value={search} onChange={e=>setSearch(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="productGrid">{shown.map(p=>{const profit=p.price-p.cost,margin=p.cost?profit/p.cost*100:0;const critical=p.track_stock&&p.stock<=p.min_stock;return <article className={`productCard ${!p.active?"inactive":""}`} key={p.id}><div className="productTop"><div className="productImage">{p.image_url?<img src={p.image_url}/>:<span>{p.name.slice(0,1).toUpperCase()}</span>}</div><div><span className="pill">{p.category||"Outros"}</span><h3>{p.name}</h3><small>{p.code||`PROD-${String(p.id).padStart(4,"0")}`}</small></div></div><div className="priceRow"><div><span>Custo</span><b>{money(p.cost)}</b></div><div><span>Venda</span><b>{money(p.price)}</b></div><div><span>Lucro</span><b>{money(profit)}</b></div><div><span>Margem</span><b>{margin.toFixed(1)}%</b></div></div><div className="stockBox"><div><span>Estoque</span><b className={critical?"critical":""}>{p.track_stock?`${p.stock} ${p.unit||"un"}`:"Não controlado"}</b></div><small>Mínimo: {p.min_stock} {p.unit||"un"}</small></div><div className="meta"><span>Produção: <b>{p.sector}</b></span><span>Impressão: <b>{p.printer||"Nenhuma"}</b></span></div><div className="cardActions"><button className="secondary" onClick={()=>startEdit(p)}>Editar</button><button className="secondary" onClick={()=>{setStockModal(p);setStockForm({qty:0,movement_type:"entry",note:""})}}>Estoque</button>{p.active&&<button className="ghostDanger" onClick={()=>deactivate(p)}>Desativar</button>}</div></article>})}</div>
  {open&&<Modal title={editing?"Editar produto":"Novo produto"} close={()=>setOpen(false)}><ProductForm form={form} setForm={setForm}/><div className="modalActions"><button className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button onClick={save}>Salvar produto</button></div></Modal>}
  {stockModal&&<Modal title={`Ajustar estoque — ${stockModal.name}`} close={()=>setStockModal(null)}><div className="formGrid"><label>Quantidade (+ entrada / - saída)<input type="number" value={stockForm.qty} onChange={e=>setStockForm({...stockForm,qty:e.target.value})}/></label><label>Tipo<select value={stockForm.movement_type} onChange={e=>setStockForm({...stockForm,movement_type:e.target.value})}><option value="entry">Entrada</option><option value="loss">Perda</option><option value="adjustment">Ajuste</option><option value="return">Devolução</option></select></label><label className="full">Observação<input value={stockForm.note} onChange={e=>setStockForm({...stockForm,note:e.target.value})} placeholder="Ex.: compra do fornecedor"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setStockModal(null)}>Cancelar</button><button onClick={adjust}>Confirmar ajuste</button></div></Modal>}
 </>
}

function ProductForm({form,setForm}){const set=(k,v)=>setForm({...form,[k]:v});return <div className="formGrid"><label>Nome do produto<input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Ex.: Espeto de carne"/></label><label>Código interno<input value={form.code||""} onChange={e=>set("code",e.target.value)} placeholder="ESP-CARNE"/></label><label>Categoria<select value={form.category} onChange={e=>set("category",e.target.value)}><option>Espetos</option><option>Cervejas</option><option>Chopp</option><option>Refrigerantes</option><option>Porções</option><option>Drinks</option><option>Sobremesas</option><option>Outros</option></select></label><label>Setor de produção<select value={form.sector} onChange={e=>set("sector",e.target.value)}><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option><option>Fritadeira</option><option>Sem produção</option></select></label><label>Custo<input type="number" step="0.01" value={form.cost} onChange={e=>set("cost",e.target.value)}/></label><label>Preço de venda<input type="number" step="0.01" value={form.price} onChange={e=>set("price",e.target.value)}/></label><label>Estoque atual<input type="number" step="0.01" value={form.stock} onChange={e=>set("stock",e.target.value)}/></label><label>Estoque mínimo<input type="number" step="0.01" value={form.min_stock} onChange={e=>set("min_stock",e.target.value)}/></label><label>Unidade<select value={form.unit} onChange={e=>set("unit",e.target.value)}><option value="un">un</option><option value="espeto">espeto</option><option value="garrafa">garrafa</option><option value="copo">copo</option><option value="porção">porção</option><option value="kg">kg</option><option value="litro">litro</option></select></label><label>Impressora<select value={form.printer} onChange={e=>set("printer",e.target.value)}><option>Nenhuma</option><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option></select></label><label className="full">URL da foto<input value={form.image_url||""} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label className="full">Descrição<textarea value={form.description||""} onChange={e=>set("description",e.target.value)} placeholder="Descrição opcional"/></label><label className="check"><input type="checkbox" checked={form.track_stock} onChange={e=>set("track_stock",e.target.checked)}/> Controlar estoque</label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/> Produto ativo</label></div>}
const Modal=({title,close,children})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={close}>×</button></div>{children}</div></div>;


function WaiterApp({tables,products,request}){
 const physical=[...Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`),...Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)];
 const[selectedName,setSelectedName]=useState(""),[selectedComanda,setSelectedComanda]=useState(null),[newCustomer,setNewCustomer]=useState(""),[showCustomer,setShowCustomer]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState("Todos"),[cart,setCart]=useState([]),[note,setNote]=useState("");
 const table=tables.find(t=>t.name===selectedName&&t.status==="open");
 useEffect(()=>{if(table&&selectedComanda){const fresh=(table.comandas||[]).find(c=>c.id===selectedComanda.id);if(fresh)setSelectedComanda(fresh)}},[tables,selectedName]);
 const categories=["Todos",...Array.from(new Set(products.map(p=>p.category||"Outros")))];
 const shown=products.filter(p=>(category==="Todos"||(p.category||"Outros")===category)&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())).slice(0,60);
 const openPlace=async name=>{setSelectedName(name);const existing=tables.find(t=>t.name===name&&t.status==="open");if(existing){const c=(existing.comandas||[]).find(x=>x.status==="open")||existing.comandas?.[0];setSelectedComanda(c||null);if(!c)setShowCustomer(true)}else{setSelectedComanda(null);setShowCustomer(true)}};
 const createCustomer=async()=>{if(!newCustomer.trim())return alert("Informe o nome do cliente.");let active=table;if(!active){active=await request("/tables/open",{method:"POST",body:JSON.stringify({name:selectedName,customer_name:newCustomer.trim()})})}const c=await request(`/tables/${active.id}/comandas`,{method:"POST",body:JSON.stringify({customer_name:newCustomer.trim(),name:""})});setSelectedComanda(c);setNewCustomer("");setShowCustomer(false)};
 const addCart=p=>setCart(current=>{const found=current.find(x=>x.product.id===p.id&&x.note===note);return found?current.map(x=>x===found?{...x,qty:x.qty+1}:x):[...current,{product:p,qty:1,note}]});
 const changeQty=(idx,delta)=>setCart(current=>current.map((x,i)=>i===idx?{...x,qty:Math.max(1,x.qty+delta)}:x));
 const removeCart=idx=>setCart(current=>current.filter((_,i)=>i!==idx));
 const sendOrder=async()=>{if(!selectedComanda)return alert("Crie ou selecione uma comanda.");if(!cart.length)return alert("Adicione produtos ao pedido.");for(const row of cart){await request(`/comandas/${selectedComanda.id}/items`,{method:"POST",body:JSON.stringify({product_id:row.product.id,qty:row.qty,note:row.note})})}setCart([]);setNote("");alert("Pedido enviado para produção.")};
 const reset=()=>{setSelectedName("");setSelectedComanda(null);setCart([]);setSearch("");setCategory("Todos");setNote("")};
 if(!selectedName)return <div className="waiterApp"><div className="waiterIntro"><div><span>Modo rápido</span><h2>Selecione a mesa</h2><p>Feito para lançar pedidos pelo celular sem passar pelo caixa.</p></div><div className="waiterStats"><b>{tables.filter(t=>t.status==="open").length}</b><span>ocupadas agora</span></div></div><div className="waiterTableGrid">{physical.map(name=>{const t=tables.find(x=>x.name===name&&x.status==="open");return <button key={name} className={`waiterTable ${t?"busy":"free"}`} onClick={()=>openPlace(name)}><strong>{name}</strong><span>{t?`${(t.comandas||[]).filter(c=>c.status==="open").length} comanda(s)`:"Livre"}</span>{t&&<b>{money(t.total)}</b>}</button>})}</div></div>;
 return <div className="waiterApp">
  <div className="waiterTop"><button className="secondary" onClick={reset}>← Mesas</button><div><span>Pedido em</span><h2>{selectedName}</h2></div><button onClick={()=>setShowCustomer(true)}>+ Cliente</button></div>
  {table&&(table.comandas||[]).length>0&&<div className="waiterCustomers">{(table.comandas||[]).filter(c=>c.status==="open").map(c=><button key={c.id} className={selectedComanda?.id===c.id?"active":""} onClick={()=>setSelectedComanda(c)}><span>{c.customer_name||c.name}</span><b>{money(c.total)}</b></button>)}</div>}
  {!selectedComanda&&<div className="waiterEmpty"><h3>Nenhuma comanda selecionada</h3><p>Crie a primeira comanda para começar o pedido.</p><button onClick={()=>setShowCustomer(true)}>Criar comanda</button></div>}
  {selectedComanda&&<div className="waiterLayout"><section className="waiterMenu"><div className="waiterSearch"><input placeholder="Buscar produto..." value={search} onChange={e=>setSearch(e.target.value)}/><input placeholder="Observação geral deste item" value={note} onChange={e=>setNote(e.target.value)}/></div><div className="waiterCategories">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="waiterProducts">{shown.map(p=><button key={p.id} onClick={()=>addCart(p)}><span>{p.name}</span><small>{p.sector}</small><b>{money(p.price)}</b></button>)}</div></section>
   <aside className="waiterCart"><div className="sectionHead"><div><h3>Pedido</h3><p>{selectedComanda.customer_name||selectedComanda.name}</p></div><span>{cart.reduce((a,x)=>a+x.qty,0)} item(ns)</span></div><div className="waiterCartItems">{cart.length===0?<div className="emptyState">Toque nos produtos para adicionar.</div>:cart.map((x,i)=><div className="waiterCartItem" key={`${x.product.id}-${i}`}><div><b>{x.product.name}</b><small>{x.note||x.product.sector}</small></div><div className="qtyStepper"><button onClick={()=>changeQty(i,-1)}>−</button><span>{x.qty}</span><button onClick={()=>changeQty(i,1)}>+</button></div><strong>{money(x.qty*x.product.price)}</strong><button className="removeMini" onClick={()=>removeCart(i)}>×</button></div>)}</div><div className="waiterTotal"><span>Total do pedido</span><b>{money(cart.reduce((a,x)=>a+x.qty*x.product.price,0))}</b></div><button className="sendOrder" onClick={sendOrder}>Enviar pedido</button></aside>
  </div>}
  {showCustomer&&<div className="modalBack"><div className="innerModal waiterCustomerModal"><h3>Nova comanda em {selectedName}</h3><input autoFocus placeholder="Nome do cliente" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&createCustomer()}/><div className="modalActions"><button className="secondary" onClick={()=>setShowCustomer(false)}>Cancelar</button><button onClick={createCustomer}>Criar comanda</button></div></div></div>}
 </div>
}

function Tables({tables,products,request}){
 const[selectedName,setSelectedName]=useState(null),[openName,setOpenName]=useState(""),[customer,setCustomer]=useState(""),[filter,setFilter]=useState("Todos"),[search,setSearch]=useState("");
 const physical=useMemo(()=>Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`).concat(Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)),[]);
 const normalized=useMemo(()=>physical.map(name=>tables.find(t=>t.name===name)||{id:null,name,status:"free",customer_name:"",total:0,comandas:[]}),[tables,physical]);
 const selected=normalized.find(t=>t.name===selectedName)||null;
 const free=normalized.filter(t=>t.status==="free").length,open=normalized.filter(t=>t.status==="open").length,total=normalized.reduce((a,t)=>a+(t.total||0),0),commands=normalized.reduce((a,t)=>a+(t.comandas||[]).filter(c=>c.status==="open").length,0);
 const shown=normalized.filter(t=>(filter==="Todos"||(filter==="Mesas"&&t.name.startsWith("Mesa"))||(filter==="Bistrôs"&&t.name.startsWith("Bistrô"))||(filter==="Livres"&&t.status==="free")||(filter==="Ocupadas"&&t.status==="open"))&&t.name.toLowerCase().includes(search.toLowerCase()));
 const choose=t=>{setSelectedName(t.name);setOpenName(t.name);setCustomer("")};
 const openTable=async()=>{await request("/tables",{method:"POST",body:JSON.stringify({name:openName,customer_name:customer.trim()||"Cliente"})});setSelectedName(null)};
 return <>
  <div className="cards tableStats"><div className="card"><span>Mesas livres</span><b>{free}</b></div><div className="card"><span>Mesas ocupadas</span><b>{open}</b></div><div className="card"><span>Comandas abertas</span><b>{commands}</b></div><div className="card"><span>Total em aberto</span><b>{money(total)}</b></div></div>
  <div className="salonToolbar"><div className="tableFilters">{["Todos","Mesas","Bistrôs","Livres","Ocupadas"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar mesa ou bistrô"/></div>
  <div className="tableLegend"><span><i className="dot free"></i>Livre</span><span><i className="dot busy"></i>Ocupada</span><span className="legendHelp">Clique em um card para abrir ou acessar a comanda</span></div>
  <div className="salonSection"><div className="salonTitle"><div><h2>Mapa do salão</h2><p>20 mesas e 4 bistrôs</p></div><strong>{open}/24 ocupados</strong></div><div className="tableGrid professionalGrid">{shown.map(t=>{const openComandas=(t.comandas||[]).filter(c=>c.status==="open");const client=openComandas[0]?.customer_name||t.customer_name||"Cliente";const itemCount=openComandas.reduce((n,c)=>n+(c.items||[]).reduce((q,i)=>q+Number(i.qty||0),0),0);return <button key={t.name} className={`tableTile ${t.status}`} onClick={()=>choose(t)}><div className="tileTop"><span className="tableIcon">{t.name.startsWith("Bistrô")?"B":"M"}</span><span className={`occupancy ${t.status}`}>{t.status==="free"?"Livre":"Ocupada"}</span></div><b>{t.name}</b>{t.status==="free"?<><small>Disponível para atendimento</small><strong>+ Abrir mesa</strong></>:<><small className="clientName">{client}</small><div className="tileMeta"><span>{openComandas.length} comanda(s)</span><span>{itemCount} item(ns)</span></div><strong>{money(t.total)}</strong></>}</button>})}</div>{shown.length===0&&<div className="emptyState salonEmpty">Nenhuma mesa encontrada.</div>}</div>
  {selected&&selected.status==="free"&&<Modal title={`Abrir ${selected.name}`} close={()=>setSelectedName(null)}><div className="openTableHero"><div className="tableIcon bigIcon">{selected.name.startsWith("Bistrô")?"B":"M"}</div><div><h3>{selected.name}</h3><p>Informe o primeiro cliente. Depois você poderá criar comandas individuais.</p></div></div><div className="formGrid"><label>Mesa<input value={openName} disabled/></label><label>Primeiro cliente<input autoFocus value={customer} onChange={e=>setCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&openTable()} placeholder="Ex.: João ou Mesa avulsa"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setSelectedName(null)}>Cancelar</button><button onClick={openTable}>Abrir mesa</button></div></Modal>}
  {selected&&selected.status==="open"&&<TableWorkspace table={selected} products={products} request={request} close={()=>setSelectedName(null)}/>} 
 </>
}
const statusInfo={waiting:{label:"Aguardando",icon:"●"},preparing:{label:"Em preparo",icon:"●"},ready:{label:"Pronto",icon:"●"},delivered:{label:"Entregue",icon:"●"}};

function TableWorkspace({table,products,request,close}){
 const[tab,setTab]=useState((table.comandas||[]).find(c=>c.status==="open")||table.comandas?.[0]||null),[newCustomer,setNewCustomer]=useState(""),[showNew,setShowNew]=useState(false),[search,setSearch]=useState(""),[qty,setQty]=useState(1),[note,setNote]=useState(""),[payment,setPayment]=useState("Pix"),[editingItem,setEditingItem]=useState(null),[editQty,setEditQty]=useState(1),[editNote,setEditNote]=useState(""),[showTransfer,setShowTransfer]=useState(false),[targetTable,setTargetTable]=useState("");
 useEffect(()=>{setTab((table.comandas||[]).find(c=>c.id===tab?.id)||(table.comandas||[]).find(c=>c.status==="open")||table.comandas?.[0]||null)},[table]);
 const shown=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())).slice(0,30);
 const addComanda=async()=>{await request(`/tables/${table.id}/comandas`,{method:"POST",body:JSON.stringify({customer_name:newCustomer,name:""})});setShowNew(false);setNewCustomer("")};
 const addItem=async p=>{if(!tab)return;await request(`/comandas/${tab.id}/items`,{method:"POST",body:JSON.stringify({product_id:p.id,qty:+qty,note})});setQty(1);setNote("")};
 const cancelItem=async i=>{if(confirm(`Cancelar ${i.qty}x ${i.product_name}? O estoque será devolvido.`))await request(`/items/${i.id}`,{method:"DELETE"})};
 const duplicateItem=async i=>{await request(`/items/${i.id}/duplicate`,{method:"POST",body:"{}"})};
 const beginEdit=i=>{setEditingItem(i);setEditQty(i.qty);setEditNote(i.note||"")};
 const saveEdit=async()=>{await request(`/items/${editingItem.id}`,{method:"PUT",body:JSON.stringify({qty:+editQty,note:editNote})});setEditingItem(null)};
 const markDelivered=async i=>{await request(`/production/${i.id}/delivered`,{method:"POST",body:"{}"})};
 const closeTab=async()=>{if(!tab)return;if(confirm(`Fechar a comanda de ${tab.customer_name} em ${payment}?`)){await request(`/comandas/${tab.id}/close`,{method:"POST",body:JSON.stringify({payment_method:payment})});close()}};
 const closeWholeTable=async()=>{if(confirm(`Fechar TODAS as comandas de ${table.name} em ${payment}?`)){await request(`/tables/${table.id}/close`,{method:"POST",body:JSON.stringify({payment_method:payment})});close()}};
 const transferTable=async()=>{if(!targetTable)return;await request(`/tables/${table.id}/transfer`,{method:"POST",body:JSON.stringify({target_name:targetTable})});setShowTransfer(false);close()};
 return <div className="modalBack"><div className="modal tableModal"><div className="modalHead"><div><h2>{table.name}</h2><p>{money(table.total)} em aberto</p></div><div className="tableHeadActions"><button className="secondary compact" onClick={()=>setShowTransfer(true)}>Transferir mesa</button><button className="iconBtn" onClick={close}>×</button></div></div>
  <div className="workspace">
   <section className="tabsPane"><div className="sectionHead"><h3>Comandas</h3><button onClick={()=>setShowNew(true)}>+ Nova</button></div><div className="tabsList">{(table.comandas||[]).map(c=><button key={c.id} className={`tabCard ${tab?.id===c.id?"selected":""} ${c.status}`} onClick={()=>setTab(c)}><span>{c.customer_name||c.name}</span><small>{c.status==="open"?"Aberta":"Fechada"}</small><b>{money(c.total)}</b></button>)}</div></section>
   <section className="orderPane">{tab?<><div className="orderHeader"><div><span>Cliente</span><h3>{tab.customer_name||tab.name}</h3></div><div><span>Total</span><strong>{money(tab.total)}</strong></div></div>{tab.status==="open"&&<><div className="quickAdd"><input placeholder="Buscar produto" value={search} onChange={e=>setSearch(e.target.value)}/><input className="qty" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><input placeholder="Observação: bem passado, sem sal..." value={note} onChange={e=>setNote(e.target.value)}/></div><div className="menuProducts">{shown.map(p=><button key={p.id} onClick={()=>addItem(p)}><span>{p.name}</span><small>{p.sector}</small><b>{money(p.price)}</b></button>)}</div></>}
   <div className="orderItems">{(tab.items||[]).length===0?<div className="emptyState">Nenhum item nesta comanda.</div>:(tab.items||[]).map(i=>{const st=statusInfo[i.status]||statusInfo.waiting;return <div className={`orderItem professional ${i.status}`} key={i.id}><div className="itemMain"><div className="itemTitle"><b>{i.qty}x {i.product_name}</b><span className={`statusBadge ${i.status}`}>{st.icon} {st.label}</span></div><small>{i.sector}{i.note?` • ${i.note}`:""}</small><div className="itemActions">{tab.status==="open"&&!i.paid&&<><button className="smallBtn" onClick={()=>beginEdit(i)}>Editar</button><button className="smallBtn" onClick={()=>duplicateItem(i)}>Duplicar</button>{i.status==="ready"&&<button className="smallBtn success" onClick={()=>markDelivered(i)}>Entregue</button>}<button className="smallBtn dangerText" onClick={()=>cancelItem(i)}>Cancelar</button></>}</div></div><strong>{money(i.qty*i.unit_price)}</strong></div>})}</div>
   {tab.status==="open"&&<div className="checkout"><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Pix</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Vale</option></select><button onClick={closeTab}>Fechar comanda — {money(tab.total)}</button><button className="closeAll" onClick={closeWholeTable}>Fechar mesa inteira — {money(table.total)}</button></div>}</>:<div className="emptyState">Crie uma comanda para começar.</div>}</section>
  </div>
  {showNew&&<div className="innerModal"><h3>Nova comanda</h3><input autoFocus placeholder="Nome do cliente" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addComanda()}/><div className="modalActions"><button className="secondary" onClick={()=>setShowNew(false)}>Cancelar</button><button onClick={addComanda}>Criar comanda</button></div></div>}
  {editingItem&&<div className="innerModal"><h3>Editar item</h3><p>{editingItem.product_name}</p><div className="formGrid"><label>Quantidade<input type="number" min="1" value={editQty} onChange={e=>setEditQty(e.target.value)}/></label><label className="full">Observação<input autoFocus value={editNote} onChange={e=>setEditNote(e.target.value)} placeholder="Ex.: bem passado"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setEditingItem(null)}>Cancelar</button><button onClick={saveEdit}>Salvar alteração</button></div></div>}
  {showTransfer&&<div className="innerModal"><h3>Transferir {table.name}</h3><p>Todos os clientes, comandas e pedidos serão movidos juntos.</p><select autoFocus value={targetTable} onChange={e=>setTargetTable(e.target.value)}><option value="">Escolha a mesa de destino</option>{Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`).concat(Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)).filter(n=>n!==table.name).map(n=><option key={n}>{n}</option>)}</select><div className="modalActions"><button className="secondary" onClick={()=>setShowTransfer(false)}>Cancelar</button><button onClick={transferTable}>Confirmar transferência</button></div></div>}
 </div></div>
}
function Production({items,printJobs,request}){
 const sectors=["Bar","Churrasqueira","Cozinha","Fritadeira"];
 const[sector,setSector]=useState("Todos"),[tick,setTick]=useState(Date.now());
 useEffect(()=>{const x=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(x)},[]);
 const visible=sector==="Todos"?items:items.filter(i=>i.sector===sector);
 const nextStatus=i=>i.status==="waiting"?"preparing":i.status==="preparing"?"ready":"delivered";
 const nextLabel=i=>i.status==="waiting"?"Iniciar preparo":i.status==="preparing"?"Marcar pronto":"Marcar entregue";
 const elapsed=i=>{const sec=Math.max(0,Math.floor((tick-new Date(i.created_at).getTime())/1000));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`};
 const pendingFor=s=>printJobs.filter(j=>s==="Todos"||j.sector===s);
 const printSector=async s=>{
   const jobs=pendingFor(s);if(!jobs.length)return alert("Não há pedidos pendentes para imprimir.");
   const grouped={};jobs.forEach(j=>{const k=`${j.table_name} — ${j.customer_name}`;(grouped[k]??=[]).push(j)});
   const body=Object.entries(grouped).map(([title,rows])=>`<section><h2>${title}</h2><p>${new Date().toLocaleString("pt-BR")}</p>${rows.map(r=>`<div class="item"><b>${r.qty}x ${r.product_name}</b>${r.note?`<small>OBS: ${r.note}</small>`:""}</div>`).join("")}</section>`).join("");
   const w=window.open("","_blank","width=420,height=700");
   if(!w)return alert("O navegador bloqueou a janela de impressão.");
   w.document.write(`<html><head><title>Produção ${s}</title><style>body{font-family:monospace;padding:12px;color:#000}h1{text-align:center;border-bottom:2px dashed #000;padding-bottom:10px}section{border-bottom:2px dashed #000;padding:10px 0}h2{margin:0 0 4px}.item{font-size:17px;margin:10px 0}.item small{display:block;font-size:13px;margin-top:3px}</style></head><body><h1>REI'SPETOS — ${s}</h1>${body}</body></html>`);
   w.document.close();w.focus();setTimeout(()=>w.print(),250);
   for(const j of jobs)await request(`/print-jobs/${j.id}/printed`,{method:"POST",body:"{}"});
 };
 const reprint=async i=>{await request(`/production/${i.id}/reprint`,{method:"POST",body:"{}"})};
 return <div className="kds">
  <div className="productionSummary"><span><b>{items.filter(i=>i.status==="waiting").length}</b> aguardando</span><span><b>{items.filter(i=>i.status==="preparing").length}</b> em preparo</span><span><b>{items.filter(i=>i.status==="ready").length}</b> prontos</span><span><b>{printJobs.length}</b> para imprimir</span></div>
  <div className="kdsToolbar"><div className="filters">{["Todos",...sectors].map(s=><button key={s} className={sector===s?"active":""} onClick={()=>setSector(s)}>{s}</button>)}</div><button className="printBtn" onClick={()=>printSector(sector)}>🖨 Imprimir pendentes ({pendingFor(sector).length})</button></div>
  <div className="grid2 productionGrid">{sectors.filter(s=>sector==="Todos"||s===sector).map(s=><div className="panel productionPanel" key={s}><div className="productionHead"><h3>{s}</h3><span>{visible.filter(i=>i.sector===s).length} pedido(s)</span></div>{visible.filter(i=>i.sector===s).length===0?<div className="emptyState">Nenhum pedido neste setor.</div>:visible.filter(i=>i.sector===s).map(i=>{const st=statusInfo[i.status]||statusInfo.waiting;const mins=Math.floor((tick-new Date(i.created_at).getTime())/60000);return <div className={`productionTicket ${i.status} ${mins>=15?"urgent":""}`} key={i.id}><div className="ticketTop"><div><strong>{i.table_name}</strong><small>{i.customer_name}</small></div><div className="ticketMeta"><span className={`timer ${mins>=15?"late":""}`}>⏱ {elapsed(i)}</span><span className={`statusBadge ${i.status}`}>{st.icon} {st.label}</span></div></div><h4>{i.qty}x {i.product_name}</h4>{i.note&&<p className="ticketNote">Obs.: {i.note}</p>}<div className="ticketActions"><button onClick={()=>request(`/production/${i.id}/${nextStatus(i)}`,{method:"POST",body:"{}"})}>{nextLabel(i)}</button><button className="secondary" onClick={()=>reprint(i)}>🖨 Reimprimir</button></div></div>})}</div>)}</div>
  <p className="printNotice">A impressão abre a caixa de diálogo do navegador. Impressão silenciosa automática exige um conector local da impressora, que será configurado em uma etapa posterior.</p>
 </div>
}
function Cash({data,request}){
 const[opening,setOpening]=useState(0),[move,setMove]=useState({movement_type:"supply",amount:0,note:""}),[counted,setCounted]=useState(0);
 const labels={supply:"Suprimento",withdrawal:"Sangria",expense:"Despesa"};
 const openCash=async()=>{await request("/cash/open",{method:"POST",body:JSON.stringify({opening_amount:+opening})});setOpening(0)};
 const addMove=async()=>{await request("/cash/movement",{method:"POST",body:JSON.stringify({...move,amount:+move.amount})});setMove({movement_type:"supply",amount:0,note:""})};
 const closeCash=async()=>{if(confirm(`Fechar o caixa com ${money(counted)} contado?`)){await request("/cash/close",{method:"POST",body:JSON.stringify({counted_amount:+counted})});setCounted(0)}};
 if(!data.open)return <><div className="cashHero closed"><div><span>Status do caixa</span><h2>Caixa fechado</h2><p>Informe o fundo inicial para começar o expediente.</p></div><div className="cashOpenForm"><label>Fundo inicial<input type="number" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)}/></label><button onClick={openCash}>Abrir caixa</button></div></div></>;
 return <div className="cashPage">
  <div className="cards cashCards">
   <div className="card"><span>Fundo inicial</span><b>{money(data.session?.opening_amount)}</b></div>
   <div className="card"><span>Vendas desde a abertura</span><b>{money(data.sales_total)}</b></div>
   <div className="card"><span>Suprimentos</span><b>{money(data.supplies)}</b></div>
   <div className="card"><span>Saídas</span><b>{money(data.withdrawals)}</b></div>
   <div className="card highlight"><span>Saldo esperado</span><b>{money(data.expected_amount)}</b></div>
  </div>
  <div className="grid2 cashGrid">
   <section className="panel">
    <div className="sectionHead"><div><h3>Movimentar caixa</h3><p>Registre toda entrada ou saída fora das vendas.</p></div></div>
    <div className="formGrid">
     <label>Tipo<select value={move.movement_type} onChange={e=>setMove({...move,movement_type:e.target.value})}><option value="supply">Suprimento</option><option value="withdrawal">Sangria</option><option value="expense">Despesa paga</option></select></label>
     <label>Valor<input type="number" step="0.01" value={move.amount} onChange={e=>setMove({...move,amount:e.target.value})}/></label>
     <label className="full">Motivo / observação<input value={move.note} onChange={e=>setMove({...move,note:e.target.value})} placeholder="Ex.: troco adicional, retirada para cofre..."/></label>
    </div>
    <button onClick={addMove}>Registrar movimentação</button>
   </section>
   <section className="panel cashClose">
    <h3>Fechamento do caixa</h3><p>Conte o dinheiro e informe o total real disponível no caixa.</p>
    <label>Valor contado<input type="number" step="0.01" value={counted} onChange={e=>setCounted(e.target.value)}/></label>
    <div className="expectedLine"><span>Esperado pelo sistema</span><b>{money(data.expected_amount)}</b></div>
    <button className="danger" onClick={closeCash}>Fechar caixa</button>
   </section>
  </div>
  <section className="panel"><div className="sectionHead"><h3>Movimentações do expediente</h3><span>{(data.movements||[]).length} registro(s)</span></div>
   <div className="cashMovements">{(data.movements||[]).length===0?<div className="emptyState">Nenhuma movimentação manual.</div>:(data.movements||[]).map(x=><div className={`cashMovement ${x.movement_type}`} key={x.id}><div><b>{labels[x.movement_type]||x.movement_type}</b><small>{x.note||"Sem observação"} • {x.username}</small></div><strong>{x.movement_type==="supply"?"+":"-"} {money(x.amount)}</strong></div>)}</div>
  </section>
 </div>
}


function Reports({request}){
 const[days,setDays]=useState(30),[report,setReport]=useState(null),[loading,setLoading]=useState(false);
 const load=async d=>{setLoading(true);try{setReport(await request(`/reports/summary?days=${d}`,{method:"GET"}))}finally{setLoading(false)}};
 useEffect(()=>{load(days)},[]);
 const change=d=>{setDays(d);load(d)};
 const maxDaily=Math.max(1,...(report?.daily||[]).map(x=>x.value));
 if(!report)return <div className="panel">{loading?"Carregando relatório...":"Sem dados disponíveis."}</div>;
 return <div className="reportsPage">
  <div className="reportToolbar"><div><h2>Visão gerencial</h2><p>Vendas, lucro, ticket médio e produtos mais vendidos.</p></div><div className="periodButtons">{[7,30,90].map(d=><button key={d} className={days===d?"active":""} onClick={()=>change(d)}>{d} dias</button>)}</div></div>
  <div className="cards reportCards">
   <div className="card"><span>Faturamento</span><b>{money(report.revenue)}</b></div>
   <div className="card"><span>Lucro estimado</span><b>{money(report.profit)}</b><small>Margem {Number(report.margin||0).toFixed(1)}%</small></div>
   <div className="card"><span>Ticket médio</span><b>{money(report.ticket_average)}</b><small>{report.sales_count} venda(s)</small></div>
   <div className="card"><span>CMV</span><b>{money(report.cost)}</b><small>Custos dos produtos</small></div>
   <div className="card"><span>Despesas pagas</span><b>{money(report.expenses)}</b></div>
  </div>
  <div className="grid2 reportGrid">
   <section className="panel"><div className="sectionHead"><div><h3>Faturamento diário</h3><p>Movimento dos últimos {report.period_days} dias.</p></div></div><div className="dailyChart">{(report.daily||[]).length===0?<div className="emptyState">Ainda não existem vendas neste período.</div>:(report.daily||[]).map(x=><div className="dailyBar" key={x.date} title={`${x.date}: ${money(x.value)}`}><div className="barValue">{money(x.value)}</div><div className="barTrack"><span style={{height:`${Math.max(5,x.value/maxDaily*100)}%`}}></span></div><small>{x.date.slice(5)}</small></div>)}</div></section>
   <section className="panel"><div className="sectionHead"><div><h3>Formas de pagamento</h3><p>Participação no faturamento.</p></div></div><div className="paymentReport">{(report.payments||[]).length===0?<div className="emptyState">Nenhum pagamento registrado.</div>:(report.payments||[]).map(x=>{const pct=report.revenue?x.value/report.revenue*100:0;return <div className="paymentRow" key={x.name}><div><b>{x.name}</b><span>{money(x.value)}</span></div><div className="paymentTrack"><span style={{width:`${pct}%`}}></span></div><small>{pct.toFixed(1)}%</small></div>})}</div></section>
  </div>
  <section className="panel"><div className="sectionHead"><div><h3>Produtos mais vendidos</h3><p>Ranking por quantidade no período.</p></div></div><div className="reportTable"><div className="reportTableHead"><span>Produto</span><span>Quantidade</span><span>Faturamento</span><span>Lucro estimado</span></div>{(report.top_products||[]).length===0?<div className="emptyState">Nenhum produto vendido neste período.</div>:(report.top_products||[]).map((x,i)=><div className="reportTableRow" key={x.name}><span><b className="rank">#{i+1}</b>{x.name}</span><span>{x.qty}</span><span>{money(x.revenue)}</span><span className="positive">{money(x.profit)}</span></div>)}</div></section>
 </div>
}

function Customers({items,request}){const[n,setN]=useState(""),[p,setP]=useState("");return <><div className="panel form"><input placeholder="Nome" value={n} onChange={e=>setN(e.target.value)}/><input placeholder="Telefone" value={p} onChange={e=>setP(e.target.value)}/><button onClick={()=>request("/customers",{method:"POST",body:JSON.stringify({name:n,phone:p})})}>Cadastrar</button></div><div className="panel">{items.map(c=><div className="item" key={c.id}><b>{c.name}</b><div>{c.phone}</div></div>)}</div></>}
function Reservations({items,request}){const[f,setF]=useState({customer_name:"",phone:"",date:"",time:"",people:2,table_name:"Mesa 01"});return <><div className="panel formGrid"><input placeholder="Cliente" onChange={e=>setF({...f,customer_name:e.target.value})}/><input placeholder="Telefone" onChange={e=>setF({...f,phone:e.target.value})}/><input type="date" onChange={e=>setF({...f,date:e.target.value})}/><input type="time" onChange={e=>setF({...f,time:e.target.value})}/><button onClick={()=>request("/reservations",{method:"POST",body:JSON.stringify(f)})}>Reservar</button></div><div className="panel">{items.map(r=><div className="item" key={r.id}><b>{r.customer_name}</b><div>{r.date} {r.time} — {r.people} pessoas</div></div>)}</div></>}
function Expenses({items,request}){const[f,setF]=useState({description:"",category:"Outros",amount:0,status:"pending"});return <><div className="panel form"><input placeholder="Descrição" onChange={e=>setF({...f,description:e.target.value})}/><input type="number" placeholder="Valor" onChange={e=>setF({...f,amount:+e.target.value})}/><button onClick={()=>request("/expenses",{method:"POST",body:JSON.stringify(f)})}>Cadastrar</button></div><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.description}</b><div>{money(x.amount)} — {x.status}</div></div>)}</div></>}
const Audit=({items})=><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.action}</b><div>{x.username} — {x.detail}</div></div>)}</div>;
createRoot(document.getElementById("root")).render(<App/>);
