import React,{useEffect,useMemo,useState}from"react";
import{API,money,blankProduct}from"./core/config";

function App(){
 const[session,setSession]=useState(null),[user,setUser]=useState("admin"),[pass,setPass]=useState("1234"),[page,setPage]=useState("dashboard"),[data,setData]=useState({}),[error,setError]=useState("");
 const api=async(path,opt={})=>{const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.token}`}:{})},...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||"Erro ao processar");return j};
 const load=async()=>{if(!session)return;const safe=async(path,fallback=[])=>{try{return await api(path)}catch(e){console.error(path,e);return fallback}};const n={products:await safe("/products"),tables:await safe("/tables"),production:await safe("/production"),printJobs:await safe("/print-jobs"),customers:await safe("/customers"),reservations:await safe("/reservations"),cash:await safe("/cash/status",{})};if(session.role==="admin"){n.dashboard=await safe("/dashboard",{});n.expenses=await safe("/expenses");n.audit=await safe("/audit")}setData(n)};
 useEffect(()=>{if(!session)return;load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[session]);
 const login=async()=>{try{setError("");const s=await api("/auth/login",{method:"POST",body:JSON.stringify({username:user,password:pass})});setSession(s);setPage(s.role==="admin"?"dashboard":"tables")}catch(e){setError(e.message)}};
 const request=async(path,opt={})=>{try{setError("");const out=await api(path,opt);await load();return out}catch(e){setError(e.message);throw e}};
 if(!session)return <div className="login"><div className="loginCard"><div className="logo">R</div><h1>REI'SPETOS OS</h1><p>Gestão operacional</p><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Usuário"/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Senha" onKeyDown={e=>e.key==="Enter"&&login()}/><button onClick={login}>Entrar</button>{error&&<div className="error">{error}</div>}<small>admin / 1234<br/>caixa / 0000</small></div></div>;
 const admin=session.role==="admin";const menu=admin?["dashboard","products","stock","tables","waiter","production","cash","finance","reports","customers","reservations","audit"]:["waiter","tables","production","cash","customers","reservations"];
 const names={dashboard:"Dashboard",products:"Produtos",stock:"Estoque",tables:"Mesas e Comandas",waiter:"App Garçom",production:"Produção",cash:"Caixa",reports:"Relatórios",customers:"Clientes",reservations:"Reservas",finance:"Financeiro",audit:"Auditoria"};
 return <div className="app"><aside><div className="brand"><div className="mini">R</div><div><b>REI'SPETOS</b><span>{admin?"Admin / Dono":"Caixa"}</span></div></div><nav>{menu.map(m=><button key={m} className={page===m?"active":""} onClick={()=>setPage(m)}>{names[m]}</button>)}</nav><button className="danger" onClick={()=>setSession(null)}>Sair</button></aside><main><div className="pageHead"><div><h1>{names[page]}</h1><p>Sistema REI'SPETOS</p></div></div>{error&&<div className="error">{error}</div>}{page==="dashboard"&&admin&&<Dashboard d={data.dashboard}/>} {page==="products"&&admin&&<Products products={data.products||[]} request={request}/>} {page==="stock"&&admin&&<Stock request={request}/>} {page==="tables"&&<Tables tables={data.tables||[]} products={(data.products||[]).filter(x=>x.active)} request={request}/>} {page==="waiter"&&<WaiterApp tables={data.tables||[]} products={(data.products||[]).filter(x=>x.active)} request={request}/>} {page==="production"&&<Production items={data.production||[]} printJobs={data.printJobs||[]} request={request}/>} {page==="cash"&&<Cash data={data.cash||{}} request={request}/>} {page==="reports"&&admin&&<Reports request={request}/>} {page==="customers"&&<Customers items={data.customers||[]} request={request}/>} {page==="reservations"&&<Reservations items={data.reservations||[]} request={request}/>} {page==="finance"&&admin&&<Finance request={request}/>} {page==="audit"&&admin&&<Audit items={data.audit||[]}/>}</main></div>
}

const Dashboard=({d})=>d?<><div className="cards"><div className="card"><span>Faturamento</span><b>{money(d.revenue)}</b></div><div className="card"><span>Lucro estimado</span><b>{money(d.profit)}</b></div><div className="card"><span>Mesas abertas</span><b>{d.open_tables}</b></div><div className="card"><span>Estoque crítico</span><b>{d.low_stock}</b></div></div><div className="panel welcome"><h2>Operação pronta</h2><p>Cadastre produtos com custo, margem, setor de produção e estoque mínimo. O próximo módulo será Mesas e Comandas individuais.</p></div></>:null;

function Products({products,request}){
 const[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blankProduct),[search,setSearch]=useState(""),[category,setCategory]=useState("Todos"),[stockModal,setStockModal]=useState(null),[stockForm,setStockForm]=useState({qty:0,movement_type:"entry",note:""});
 const cats=useMemo(()=>["Todos",...new Set(products.map(p=>p.category||"Outros"))],[products]);
 const shown=products.filter(p=>(category==="Todos"||(p.category||"Outros")===category)&&(`${p.name} ${p.code||""}`.toLowerCase().includes(search.toLowerCase())));
 const startNew=()=>{setEditing(null);setForm(blankProduct);setOpen(true)};
 const startEdit=p=>{setEditing(p);setForm({...blankProduct,...p});setOpen(true)};
 const save=async()=>{const opt={method:editing?"PUT":"POST",body:JSON.stringify({...form,cost:+form.cost,price:+form.price,stock:+form.stock,min_stock:+form.min_stock})};await request(editing?`/products/${editing.id}`:"/products",opt);setOpen(false)};
 const deactivate=async p=>{if(confirm(`Desativar ${p.name}?`))await request(`/products/${p.id}`,{method:"DELETE"})};
 const adjust=async()=>{await request(`/products/${stockModal.id}/stock`,{method:"POST",body:JSON.stringify({...stockForm,qty:+stockForm.qty})});setStockModal(null);setStockForm({qty:0,movement_type:"entry",note:""})};
 const active=products.filter(p=>p.active).length,critical=products.filter(p=>p.active&&p.track_stock&&p.stock<=p.min_stock).length,totalValue=products.reduce((s,p)=>s+(p.active?p.stock*p.cost:0),0);
 return <>
  <div className="cards productStats"><div className="card"><span>Produtos ativos</span><b>{active}</b></div><div className="card"><span>Estoque crítico</span><b>{critical}</b></div><div className="card"><span>Valor em estoque</span><b>{money(totalValue)}</b></div><div className="card actionCard"><button onClick={startNew}>+ Novo produto</button></div></div>
  <div className="toolbar"><input placeholder="Buscar produto ou código" value={search} onChange={e=>setSearch(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="productGrid">{shown.map(p=>{const profit=p.price-p.cost,margin=p.cost?profit/p.cost*100:0;const critical=p.track_stock&&p.stock<=p.min_stock;return <article className={`productCard ${!p.active?"inactive":""}`} key={p.id}><div className="productTop"><div className="productImage">{p.image_url?<img src={p.image_url}/>:<span>{p.name.slice(0,1).toUpperCase()}</span>}</div><div><span className="pill">{p.category||"Outros"}</span><h3>{p.name}</h3><small>{p.code||`PROD-${String(p.id).padStart(4,"0")}`}</small></div></div><div className="priceRow"><div><span>Custo</span><b>{money(p.cost)}</b></div><div><span>Venda</span><b>{money(p.price)}</b></div><div><span>Lucro</span><b>{money(profit)}</b></div><div><span>Margem</span><b>{margin.toFixed(1)}%</b></div></div><div className="stockBox"><div><span>Estoque</span><b className={critical?"critical":""}>{p.track_stock?`${p.stock} ${p.unit||"un"}`:"Não controlado"}</b></div><small>Mínimo: {p.min_stock} {p.unit||"un"}</small></div><div className="meta"><span>Produção: <b>{p.sector}</b></span><span>Impressão: <b>{p.printer||"Nenhuma"}</b></span></div><div className="cardActions"><button className="secondary" onClick={()=>startEdit(p)}>Editar</button><button className="secondary" onClick={()=>{setStockModal(p);setStockForm({qty:0,movement_type:"entry",note:""})}}>Estoque</button>{p.active&&<button className="ghostDanger" onClick={()=>deactivate(p)}>Desativar</button>}</div></article>})}</div>
  {open&&<Modal title={editing?"Editar produto":"Novo produto"} close={()=>setOpen(false)}><ProductForm form={form} setForm={setForm}/><div className="modalActions"><button className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button onClick={save}>Salvar produto</button></div></Modal>}
  {stockModal&&<Modal title={`Ajustar estoque — ${stockModal.name}`} close={()=>setStockModal(null)}><div className="formGrid"><label>Quantidade (+ entrada / - saída)<input type="number" value={stockForm.qty} onChange={e=>setStockForm({...stockForm,qty:e.target.value})}/></label><label>Tipo<select value={stockForm.movement_type} onChange={e=>setStockForm({...stockForm,movement_type:e.target.value})}><option value="entry">Entrada</option><option value="loss">Perda</option><option value="adjustment">Ajuste</option><option value="return">Devolução</option></select></label><label className="full">Observação<input value={stockForm.note} onChange={e=>setStockForm({...stockForm,note:e.target.value})} placeholder="Ex.: compra do fornecedor"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setStockModal(null)}>Cancelar</button><button onClick={adjust}>Confirmar ajuste</button></div></Modal>}
 </>
}

function ProductForm({form,setForm}){const set=(k,v)=>setForm({...form,[k]:v});return <div className="formGrid"><label>Nome do produto<input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Ex.: Espeto de carne"/></label><label>Código interno<input value={form.code||""} onChange={e=>set("code",e.target.value)} placeholder="ESP-CARNE"/></label><label>Categoria<select value={form.category} onChange={e=>set("category",e.target.value)}><option>Espetos</option><option>Cervejas</option><option>Chopp</option><option>Refrigerantes</option><option>Porções</option><option>Drinks</option><option>Sobremesas</option><option>Outros</option></select></label><label>Setor de produção<select value={form.sector} onChange={e=>set("sector",e.target.value)}><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option><option>Fritadeira</option><option>Sem produção</option></select></label><label>Custo<input type="number" step="0.01" value={form.cost} onChange={e=>set("cost",e.target.value)}/></label><label>Preço de venda<input type="number" step="0.01" value={form.price} onChange={e=>set("price",e.target.value)}/></label><label>Estoque atual<input type="number" step="0.01" value={form.stock} onChange={e=>set("stock",e.target.value)}/></label><label>Estoque mínimo<input type="number" step="0.01" value={form.min_stock} onChange={e=>set("min_stock",e.target.value)}/></label><label>Unidade<select value={form.unit} onChange={e=>set("unit",e.target.value)}><option value="un">un</option><option value="espeto">espeto</option><option value="garrafa">garrafa</option><option value="copo">copo</option><option value="porção">porção</option><option value="kg">kg</option><option value="litro">litro</option></select></label><label>Impressora<select value={form.printer} onChange={e=>set("printer",e.target.value)}><option>Nenhuma</option><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option></select></label><label className="full">URL da foto<input value={form.image_url||""} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label className="full">Descrição<textarea value={form.description||""} onChange={e=>set("description",e.target.value)} placeholder="Descrição opcional"/></label><label className="check"><input type="checkbox" checked={form.track_stock} onChange={e=>set("track_stock",e.target.checked)}/> Controlar estoque</label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/> Produto ativo</label></div>}
const Modal=({title,close,children})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={close}>×</button></div>{children}</div></div>;


function WaiterApp({tables,products,request}){
 const physical=[...Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`),...Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)];
 const[selectedName,setSelectedName]=useState(""),[selectedComanda,setSelectedComanda]=useState(null),[newCustomer,setNewCustomer]=useState(""),[showCustomer,setShowCustomer]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState("Todos"),[cart,setCart]=useState([]),[note,setNote]=useState("");
 const table=tables.find(t=>t.name===selectedName&&t.status==="open");
 useEffect(()=>{if(table&&selectedComanda){const fresh=(table.comandas||[]).find(c=>c.id===selectedComanda.id);if(fresh)setSelectedComanda(fresh)}},[tables,selectedName]);
 const categories=["Todos",...Array.from(new Set(products.map(p=>p.category||"Outros")))];
 const shown=products.filter(p=>(category==="Todos"||(p.category||"Outros")===category)&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())).slice(0,60);
 const openPlace=async name=>{setSelectedName(name);const existing=tables.find(t=>t.name===name&&t.status==="open");if(existing){const c=(existing.comandas||[]).find(x=>x.status==="open")||existing.comandas?.[0];setSelectedComanda(c||null);if(!c)setShowCustomer(true)}else{setSelectedComanda(null);setShowCustomer(true)}};
 const createCustomer=async()=>{if(!newCustomer.trim())return alert("Informe o nome do cliente.");let active=table;if(!active){active=await request("/tables/open",{method:"POST",body:JSON.stringify({name:selectedName,customer_name:newCustomer.trim()})})}const c=await request(`/tables/${active.id}/comandas`,{method:"POST",body:JSON.stringify({customer_name:newCustomer.trim(),name:""})});setSelectedComanda(c);setNewCustomer("");setShowCustomer(false)};
 const addCart=p=>setCart(current=>{const found=current.find(x=>x.product.id===p.id&&x.note===note);return found?current.map(x=>x===found?{...x,qty:x.qty+1}:x):[...current,{product:p,qty:1,note}]});
 const changeQty=(idx,delta)=>setCart(current=>current.map((x,i)=>i===idx?{...x,qty:Math.max(1,x.qty+delta)}:x));
 const removeCart=idx=>setCart(current=>current.filter((_,i)=>i!==idx));
 const sendOrder=async()=>{if(!selectedComanda)return alert("Crie ou selecione uma comanda.");if(!cart.length)return alert("Adicione produtos ao pedido.");for(const row of cart){await request(`/comandas/${selectedComanda.id}/items`,{method:"POST",body:JSON.stringify({product_id:row.product.id,qty:row.qty,note:row.note})})}setCart([]);setNote("");alert("Pedido enviado para produção.")};
 const reset=()=>{setSelectedName("");setSelectedComanda(null);setCart([]);setSearch("");setCategory("Todos");setNote("")};
 if(!selectedName)return <div className="waiterApp"><div className="waiterIntro"><div><span>Modo rápido</span><h2>Selecione a mesa</h2><p>Feito para lançar pedidos pelo celular sem passar pelo caixa.</p></div><div className="waiterStats"><b>{tables.filter(t=>t.status==="open").length}</b><span>ocupadas agora</span></div></div><div className="waiterTableGrid">{physical.map(name=>{const t=tables.find(x=>x.name===name&&x.status==="open");return <button key={name} className={`waiterTable ${t?"busy":"free"}`} onClick={()=>openPlace(name)}><strong>{name}</strong><span>{t?`${(t.comandas||[]).filter(c=>c.status==="open").length} comanda(s)`:"Livre"}</span>{t&&<b>{money(t.total)}</b>}</button>})}</div></div>;
 return <div className="waiterApp">
  <div className="waiterTop"><button className="secondary" onClick={reset}>← Mesas</button><div><span>Pedido em</span><h2>{selectedName}</h2></div><button onClick={()=>setShowCustomer(true)}>+ Cliente</button></div>
  {table&&(table.comandas||[]).length>0&&<div className="waiterCustomers">{(table.comandas||[]).filter(c=>c.status==="open").map(c=><button key={c.id} className={selectedComanda?.id===c.id?"active":""} onClick={()=>setSelectedComanda(c)}><span>{c.customer_name||c.name}</span><b>{money(c.total)}</b></button>)}</div>}
  {!selectedComanda&&<div className="waiterEmpty"><h3>Nenhuma comanda selecionada</h3><p>Crie a primeira comanda para começar o pedido.</p><button onClick={()=>setShowCustomer(true)}>Criar comanda</button></div>}
  {selectedComanda&&<div className="waiterLayout"><section className="waiterMenu"><div className="waiterSearch"><input placeholder="Buscar produto..." value={search} onChange={e=>setSearch(e.target.value)}/><input placeholder="Observação geral deste item" value={note} onChange={e=>setNote(e.target.value)}/></div><div className="waiterCategories">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="waiterProducts">{shown.map(p=><button key={p.id} onClick={()=>addCart(p)}><span>{p.name}</span><small>{p.sector}</small><b>{money(p.price)}</b></button>)}</div></section>
   <aside className="waiterCart"><div className="sectionHead"><div><h3>Pedido</h3><p>{selectedComanda.customer_name||selectedComanda.name}</p></div><span>{cart.reduce((a,x)=>a+x.qty,0)} item(ns)</span></div><div className="waiterCartItems">{cart.length===0?<div className="emptyState">Toque nos produtos para adicionar.</div>:cart.map((x,i)=><div className="waiterCartItem" key={`${x.product.id}-${i}`}><div><b>{x.product.name}</b><small>{x.note||x.product.sector}</small></div><div className="qtyStepper"><button onClick={()=>changeQty(i,-1)}>−</button><span>{x.qty}</span><button onClick={()=>changeQty(i,1)}>+</button></div><strong>{money(x.qty*x.product.price)}</strong><button className="removeMini" onClick={()=>removeCart(i)}>×</button></div>)}</div><div className="waiterTotal"><span>Total do pedido</span><b>{money(cart.reduce((a,x)=>a+x.qty*x.product.price,0))}</b></div><button className="sendOrder" onClick={sendOrder}>Enviar pedido</button></aside>
  </div>}
  {showCustomer&&<div className="modalBack"><div className="innerModal waiterCustomerModal"><h3>Nova comanda em {selectedName}</h3><input autoFocus placeholder="Nome do cliente" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&createCustomer()}/><div className="modalActions"><button className="secondary" onClick={()=>setShowCustomer(false)}>Cancelar</button><button onClick={createCustomer}>Criar comanda</button></div></div></div>}
 </div>
}


function Stock({request}){
 const[dashboard,setDashboard]=useState(null),[products,setProducts]=useState([]),[movements,setMovements]=useState([]),[suppliers,setSuppliers]=useState([]),[purchases,setPurchases]=useState([]),[tab,setTab]=useState("dashboard"),[search,setSearch]=useState(""),[inventory,setInventory]=useState({}),[inventoryNote,setInventoryNote]=useState("Inventário geral"),[showSupplier,setShowSupplier]=useState(false),[supplierForm,setSupplierForm]=useState({name:"",contact:"",phone:"",notes:""}),[showPurchase,setShowPurchase]=useState(false),[purchaseForm,setPurchaseForm]=useState({supplier_id:"",expected_date:"",notes:"",items:[]}),[receiveOrder,setReceiveOrder]=useState(null),[receiveQty,setReceiveQty]=useState({});
 const load=async()=>{const[d,s,m,sp,po]=await Promise.all([request("/stock/dashboard",{method:"GET"}),request("/stock/summary",{method:"GET"}),request("/stock/movements?limit=300",{method:"GET"}),request("/stock/suppliers",{method:"GET"}),request("/stock/purchases",{method:"GET"})]);setDashboard(d);setProducts(s.products||[]);setMovements(m||[]);setSuppliers(sp||[]);setPurchases(po||[]);const counts={};(s.products||[]).forEach(p=>counts[p.id]=p.stock);setInventory(counts)};
 useEffect(()=>{load()},[]);
 if(!dashboard)return <div className="panel">Carregando módulo de estoque...</div>;
 const shown=products.filter(p=>`${p.name} ${p.code||""} ${p.category||""}`.toLowerCase().includes(search.toLowerCase()));
 const saveInventory=async()=>{const items=Object.entries(inventory).map(([product_id,counted])=>({product_id:+product_id,counted:+counted}));const r=await request("/stock/inventory",{method:"POST",body:JSON.stringify({items,note:inventoryNote})});alert(`${r.changed} produto(s) ajustado(s).`);await load();setTab("dashboard")};
 const saveSupplier=async()=>{await request("/stock/suppliers",{method:"POST",body:JSON.stringify(supplierForm)});setSupplierForm({name:"",contact:"",phone:"",notes:""});setShowSupplier(false);await load()};
 const addPurchaseItem=()=>setPurchaseForm({...purchaseForm,items:[...purchaseForm.items,{product_id:products[0]?.id||"",qty:1,unit_cost:products[0]?.cost||0}]});
 const changePurchaseItem=(idx,key,value)=>setPurchaseForm({...purchaseForm,items:purchaseForm.items.map((x,i)=>i===idx?{...x,[key]:value}:x)});
 const removePurchaseItem=idx=>setPurchaseForm({...purchaseForm,items:purchaseForm.items.filter((_,i)=>i!==idx)});
 const savePurchase=async()=>{await request("/stock/purchases",{method:"POST",body:JSON.stringify({...purchaseForm,supplier_id:purchaseForm.supplier_id?+purchaseForm.supplier_id:null,items:purchaseForm.items.map(x=>({...x,product_id:+x.product_id,qty:+x.qty,unit_cost:+x.unit_cost}))})});setShowPurchase(false);setPurchaseForm({supplier_id:"",expected_date:"",notes:"",items:[]});await load()};
 const openReceive=o=>{const q={};o.items.forEach(i=>q[i.id]=i.qty);setReceiveQty(q);setReceiveOrder(o)};
 const confirmReceive=async()=>{await request(`/stock/purchases/${receiveOrder.id}/receive`,{method:"POST",body:JSON.stringify({received:receiveQty})});setReceiveOrder(null);await load()};
 const cancelPurchase=async o=>{if(confirm(`Cancelar o pedido #${o.id}?`)){await request(`/stock/purchases/${o.id}/cancel`,{method:"PUT",body:"{}"});await load()}};
 const movementLabel={entry:"Entrada",loss:"Perda",adjustment:"Ajuste",return:"Devolução",inventory:"Inventário",sale:"Venda",purchase:"Compra"};
 const orderStatus={ordered:"Aguardando",received:"Recebido",cancelled:"Cancelado",draft:"Rascunho"};
 const exportCsv=()=>{const rows=[["Produto","Código","Categoria","Estoque","Mínimo","Unidade","Custo","Valor"],...products.map(p=>[p.name,p.code||"",p.category||"",p.stock,p.min_stock,p.unit||"un",p.cost,(p.stock||0)*(p.cost||0)])];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="estoque-completo-reispetos.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className="stockPro">
  <div className="stockHero"><div><span>Gestão avançada</span><h2>Estoque completo</h2><p>Compras, fornecedores, inventário, alertas e movimentações em um só lugar.</p></div><div><button className="secondary" onClick={()=>setShowSupplier(true)}>+ Fornecedor</button><button onClick={()=>{setShowPurchase(true);if(purchaseForm.items.length===0)addPurchaseItem()}}>+ Pedido de compra</button></div></div>
  <div className="cards stockProCards"><div className="card"><span>Itens controlados</span><b>{dashboard.tracked}</b></div><div className="card"><span>Críticos</span><b className={dashboard.critical?"redText":""}>{dashboard.critical}</b></div><div className="card"><span>Zerados</span><b className={dashboard.zero?"redText":""}>{dashboard.zero}</b></div><div className="card"><span>Excesso</span><b>{dashboard.excess}</b></div><div className="card"><span>Compras pendentes</span><b>{dashboard.pending_purchases}</b></div><div className="card"><span>Valor em estoque</span><b>{money(dashboard.value)}</b></div></div>
  <div className="stockProTabs">{[["dashboard","Visão geral"],["products","Produtos"],["purchases","Compras"],["suppliers","Fornecedores"],["movements","Movimentações"],["inventory","Inventário"]].map(([v,l])=><button key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{l}</button>)}<button className="secondary" onClick={exportCsv}>Exportar CSV</button></div>
  {tab==="dashboard"&&<div className="stockDashboardGrid"><section className="panel"><div className="sectionHead"><div><h3>Estoque crítico</h3><p>Itens no mínimo ou abaixo dele.</p></div><span>{dashboard.critical}</span></div><div className="alertList">{dashboard.critical_items.length===0?<div className="emptyState">Nenhum item crítico.</div>:dashboard.critical_items.map(p=><div className="stockAlert critical" key={p.id}><div><b>{p.name}</b><small>Mínimo: {p.min_stock} {p.unit||"un"}</small></div><strong>{p.stock} {p.unit||"un"}</strong></div>)}</div></section><section className="panel"><div className="sectionHead"><div><h3>Possível excesso</h3><p>Estoque quatro vezes acima do mínimo.</p></div><span>{dashboard.excess}</span></div><div className="alertList">{dashboard.excess_items.length===0?<div className="emptyState">Nenhum excesso identificado.</div>:dashboard.excess_items.map(p=><div className="stockAlert excess" key={p.id}><div><b>{p.name}</b><small>Mínimo: {p.min_stock} {p.unit||"un"}</small></div><strong>{p.stock} {p.unit||"un"}</strong></div>)}</div></section><section className="panel wide"><div className="sectionHead"><div><h3>Últimas movimentações</h3><p>Visão rápida das alterações mais recentes.</p></div></div><div className="movementList">{dashboard.latest_movements.map(m=><div className={`movementRow ${Number(m.qty)>=0?"positive":"negative"}`} key={m.id}><div><b>{m.product_name}</b><small>{movementLabel[m.movement_type]||m.movement_type} • {m.note||"Sem observação"}</small></div><strong>{Number(m.qty)>=0?"+":""}{m.qty}</strong></div>)}</div></section></div>}
  {tab==="products"&&<><div className="stockToolbar"><input placeholder="Buscar produto, código ou categoria..." value={search} onChange={e=>setSearch(e.target.value)}/><span>{shown.length} produto(s)</span></div><div className="stockGrid">{shown.map(p=>{const critical=Number(p.stock)<=Number(p.min_stock);return <article className={`stockCard ${critical?"critical":""}`} key={p.id}><div className="stockCardHead"><div><h3>{p.name}</h3><small>{p.code||`PROD-${String(p.id).padStart(4,"0")}`}</small></div><span>{p.category||"Outros"}</span></div><div className="stockAmount"><b>{p.stock}</b><span>{p.unit||"un"}</span></div><div className="stockMeta"><span>Mínimo: <b>{p.min_stock}</b></span><span>Custo: <b>{money(p.cost)}</b></span><span>Total: <b>{money((p.stock||0)*(p.cost||0))}</b></span></div>{critical&&<div className="criticalFlag">{Number(p.stock)<=0?"SEM ESTOQUE":"REPOR ESTOQUE"}</div>}</article>})}</div></>}
  {tab==="purchases"&&<section className="panel"><div className="sectionHead"><div><h3>Pedidos de compra</h3><p>Acompanhe compras pendentes e recebidas.</p></div><button onClick={()=>{setShowPurchase(true);if(purchaseForm.items.length===0)addPurchaseItem()}}>+ Novo pedido</button></div><div className="purchaseList">{purchases.length===0?<div className="emptyState">Nenhum pedido de compra.</div>:purchases.map(o=><article className={`purchaseCard ${o.status}`} key={o.id}><div><span>Pedido #{o.id}</span><h3>{o.supplier_name}</h3><small>Previsão: {o.expected_date||"Não informada"} • {o.items.length} item(ns)</small></div><div className="purchaseItems">{o.items.map(i=><span key={i.id}>{i.qty}x {i.product_name} — {money(i.unit_cost)}</span>)}</div><strong>{money(o.total)}</strong><span className={`purchaseStatus ${o.status}`}>{orderStatus[o.status]}</span><div className="purchaseActions">{o.status==="ordered"&&<><button onClick={()=>openReceive(o)}>Receber</button><button className="dangerMini" onClick={()=>cancelPurchase(o)}>Cancelar</button></>}</div></article>)}</div></section>}
  {tab==="suppliers"&&<section className="panel"><div className="sectionHead"><div><h3>Fornecedores</h3><p>Cadastros para pedidos de compra.</p></div><button onClick={()=>setShowSupplier(true)}>+ Novo fornecedor</button></div><div className="supplierGrid">{suppliers.length===0?<div className="emptyState">Nenhum fornecedor cadastrado.</div>:suppliers.map(s=><article className="supplierCard" key={s.id}><h3>{s.name}</h3><p>{s.contact||"Sem contato informado"}</p><a href={`https://wa.me/55${String(s.phone||"").replace(/\D/g,"")}`} target="_blank" rel="noreferrer">{s.phone||"Sem telefone"}</a><small>{s.notes||"Sem observações"}</small></article>)}</div></section>}
  {tab==="movements"&&<section className="panel"><div className="sectionHead"><div><h3>Histórico completo</h3><p>Entradas, perdas, compras, vendas e inventários.</p></div><span>{movements.length} registro(s)</span></div><div className="movementList">{movements.map(m=><div className={`movementRow ${Number(m.qty)>=0?"positive":"negative"}`} key={m.id}><div><b>{m.product_name}</b><small>{movementLabel[m.movement_type]||m.movement_type} • {m.note||"Sem observação"}</small></div><strong>{Number(m.qty)>=0?"+":""}{m.qty}</strong></div>)}</div></section>}
  {tab==="inventory"&&<section className="panel"><div className="sectionHead"><div><h3>Inventário físico</h3><p>Compare o estoque do sistema com a contagem real.</p></div></div><input className="inventoryNote" value={inventoryNote} onChange={e=>setInventoryNote(e.target.value)} placeholder="Motivo da contagem"/><div className="inventoryTable"><div className="inventoryHead"><span>Produto</span><span>Sistema</span><span>Contado</span><span>Diferença</span></div>{products.map(p=>{const counted=Number(inventory[p.id]??p.stock),diff=counted-Number(p.stock||0);return <div className="inventoryRow" key={p.id}><span><b>{p.name}</b><small>{p.code||""}</small></span><span>{p.stock} {p.unit||"un"}</span><input type="number" step="0.01" value={inventory[p.id]??p.stock} onChange={e=>setInventory({...inventory,[p.id]:e.target.value})}/><strong className={diff===0?"":diff>0?"positive":"negative"}>{diff>0?"+":""}{diff}</strong></div>})}</div><div className="inventoryActions"><button className="secondary" onClick={load}>Descartar</button><button onClick={saveInventory}>Concluir inventário</button></div></section>}
  {showSupplier&&<div className="modalBack"><div className="innerModal supplierModal"><h3>Novo fornecedor</h3><div className="formGrid"><label className="full">Nome<input autoFocus value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/></label><label>Contato<input value={supplierForm.contact} onChange={e=>setSupplierForm({...supplierForm,contact:e.target.value})}/></label><label>Telefone<input value={supplierForm.phone} onChange={e=>setSupplierForm({...supplierForm,phone:e.target.value})}/></label><label className="full">Observações<textarea value={supplierForm.notes} onChange={e=>setSupplierForm({...supplierForm,notes:e.target.value})}/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setShowSupplier(false)}>Cancelar</button><button onClick={saveSupplier}>Salvar fornecedor</button></div></div></div>}
  {showPurchase&&<div className="modalBack"><div className="innerModal purchaseModal"><div className="sectionHead"><div><h3>Novo pedido de compra</h3><p>Cadastre os produtos e custos negociados.</p></div></div><div className="formGrid"><label>Fornecedor<select value={purchaseForm.supplier_id} onChange={e=>setPurchaseForm({...purchaseForm,supplier_id:e.target.value})}><option value="">Sem fornecedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Previsão<input type="date" value={purchaseForm.expected_date} onChange={e=>setPurchaseForm({...purchaseForm,expected_date:e.target.value})}/></label><label className="full">Observação<input value={purchaseForm.notes} onChange={e=>setPurchaseForm({...purchaseForm,notes:e.target.value})}/></label></div><div className="purchaseBuilder">{purchaseForm.items.map((it,idx)=><div className="purchaseBuilderRow" key={idx}><select value={it.product_id} onChange={e=>{const p=products.find(x=>x.id===+e.target.value);changePurchaseItem(idx,"product_id",e.target.value);if(p)changePurchaseItem(idx,"unit_cost",p.cost)}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" min="0" step="0.01" value={it.qty} onChange={e=>changePurchaseItem(idx,"qty",e.target.value)} placeholder="Qtd"/><input type="number" min="0" step="0.01" value={it.unit_cost} onChange={e=>changePurchaseItem(idx,"unit_cost",e.target.value)} placeholder="Custo"/><button className="dangerMini" onClick={()=>removePurchaseItem(idx)}>×</button></div>)}</div><button className="secondary" onClick={addPurchaseItem}>+ Adicionar produto</button><div className="purchaseTotal">Total estimado: <b>{money(purchaseForm.items.reduce((a,x)=>a+(+x.qty||0)*(+x.unit_cost||0),0))}</b></div><div className="modalActions"><button className="secondary" onClick={()=>setShowPurchase(false)}>Cancelar</button><button onClick={savePurchase}>Criar pedido</button></div></div></div>}
  {receiveOrder&&<div className="modalBack"><div className="innerModal receiveModal"><h3>Receber pedido #{receiveOrder.id}</h3><p>{receiveOrder.supplier_name}</p><div className="receiveList">{receiveOrder.items.map(i=><label key={i.id}><span>{i.product_name}<small>Pedido: {i.qty}</small></span><input type="number" min="0" max={i.qty} step="0.01" value={receiveQty[i.id]??i.qty} onChange={e=>setReceiveQty({...receiveQty,[i.id]:e.target.value})}/></label>)}</div><div className="modalActions"><button className="secondary" onClick={()=>setReceiveOrder(null)}>Cancelar</button><button onClick={confirmReceive}>Confirmar recebimento</button></div></div></div>}
 </div>
}

function Tables({tables,products,request}){
 const[selectedName,setSelectedName]=useState(null),[openName,setOpenName]=useState(""),[customer,setCustomer]=useState(""),[filter,setFilter]=useState("Todos"),[search,setSearch]=useState("");
 const physical=useMemo(()=>Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`).concat(Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)),[]);
 const normalized=useMemo(()=>physical.map(name=>tables.find(t=>t.name===name)||{id:null,name,status:"free",customer_name:"",total:0,comandas:[]}),[tables,physical]);
 const selected=normalized.find(t=>t.name===selectedName)||null;
 const free=normalized.filter(t=>t.status==="free").length,open=normalized.filter(t=>t.status==="open").length,total=normalized.reduce((a,t)=>a+(t.total||0),0),commands=normalized.reduce((a,t)=>a+(t.comandas||[]).filter(c=>c.status==="open").length,0);
 const shown=normalized.filter(t=>(filter==="Todos"||(filter==="Mesas"&&t.name.startsWith("Mesa"))||(filter==="Bistrôs"&&t.name.startsWith("Bistrô"))||(filter==="Livres"&&t.status==="free")||(filter==="Ocupadas"&&t.status==="open"))&&t.name.toLowerCase().includes(search.toLowerCase()));
 const choose=t=>{setSelectedName(t.name);setOpenName(t.name);setCustomer("")};
 const openTable=async()=>{await request("/tables",{method:"POST",body:JSON.stringify({name:openName,customer_name:customer.trim()||"Cliente"})});setSelectedName(null)};
 return <>
  <div className="cards tableStats"><div className="card"><span>Mesas livres</span><b>{free}</b></div><div className="card"><span>Mesas ocupadas</span><b>{open}</b></div><div className="card"><span>Comandas abertas</span><b>{commands}</b></div><div className="card"><span>Total em aberto</span><b>{money(total)}</b></div></div>
  <div className="salonToolbar"><div className="tableFilters">{["Todos","Mesas","Bistrôs","Livres","Ocupadas"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar mesa ou bistrô"/></div>
  <div className="tableLegend"><span><i className="dot free"></i>Livre</span><span><i className="dot busy"></i>Ocupada</span><span className="legendHelp">Clique em um card para abrir ou acessar a comanda</span></div>
  <div className="salonSection"><div className="salonTitle"><div><h2>Mapa do salão</h2><p>20 mesas e 4 bistrôs</p></div><strong>{open}/24 ocupados</strong></div><div className="tableGrid professionalGrid">{shown.map(t=>{const openComandas=(t.comandas||[]).filter(c=>c.status==="open");const client=openComandas[0]?.customer_name||t.customer_name||"Cliente";const itemCount=openComandas.reduce((n,c)=>n+(c.items||[]).reduce((q,i)=>q+Number(i.qty||0),0),0);return <button key={t.name} className={`tableTile ${t.status}`} onClick={()=>choose(t)}><div className="tileTop"><span className="tableIcon">{t.name.startsWith("Bistrô")?"B":"M"}</span><span className={`occupancy ${t.status}`}>{t.status==="free"?"Livre":"Ocupada"}</span></div><b>{t.name}</b>{t.status==="free"?<><small>Disponível para atendimento</small><strong>+ Abrir mesa</strong></>:<><small className="clientName">{client}</small><div className="tileMeta"><span>{openComandas.length} comanda(s)</span><span>{itemCount} item(ns)</span></div><strong>{money(t.total)}</strong></>}</button>})}</div>{shown.length===0&&<div className="emptyState salonEmpty">Nenhuma mesa encontrada.</div>}</div>
  {selected&&selected.status==="free"&&<Modal title={`Abrir ${selected.name}`} close={()=>setSelectedName(null)}><div className="openTableHero"><div className="tableIcon bigIcon">{selected.name.startsWith("Bistrô")?"B":"M"}</div><div><h3>{selected.name}</h3><p>Informe o primeiro cliente. Depois você poderá criar comandas individuais.</p></div></div><div className="formGrid"><label>Mesa<input value={openName} disabled/></label><label>Primeiro cliente<input autoFocus value={customer} onChange={e=>setCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&openTable()} placeholder="Ex.: João ou Mesa avulsa"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setSelectedName(null)}>Cancelar</button><button onClick={openTable}>Abrir mesa</button></div></Modal>}
  {selected&&selected.status==="open"&&<TableWorkspace table={selected} products={products} request={request} close={()=>setSelectedName(null)}/>} 
 </>
}
const statusInfo={waiting:{label:"Aguardando",icon:"●"},preparing:{label:"Em preparo",icon:"●"},ready:{label:"Pronto",icon:"●"},delivered:{label:"Entregue",icon:"●"}};

function TableWorkspace({table,products,request,close}){
 const[tab,setTab]=useState((table.comandas||[]).find(c=>c.status==="open")||table.comandas?.[0]||null),[newCustomer,setNewCustomer]=useState(""),[showNew,setShowNew]=useState(false),[search,setSearch]=useState(""),[qty,setQty]=useState(1),[note,setNote]=useState(""),[payment,setPayment]=useState("Pix"),[editingItem,setEditingItem]=useState(null),[editQty,setEditQty]=useState(1),[editNote,setEditNote]=useState(""),[showTransfer,setShowTransfer]=useState(false),[targetTable,setTargetTable]=useState(""),[transferItem,setTransferItem]=useState(null),[targetComanda,setTargetComanda]=useState(""),[transferComandaOpen,setTransferComandaOpen]=useState(false),[servicePercent,setServicePercent]=useState(10),[discount,setDiscount]=useState(0),[mixed,setMixed]=useState(false),[payments,setPayments]=useState([{payment_method:"Pix",amount:""}]);
 useEffect(()=>{setTab((table.comandas||[]).find(c=>c.id===tab?.id)||(table.comandas||[]).find(c=>c.status==="open")||table.comandas?.[0]||null)},[table]);
 const shown=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())).slice(0,30);
 const addComanda=async()=>{await request(`/tables/${table.id}/comandas`,{method:"POST",body:JSON.stringify({customer_name:newCustomer,name:""})});setShowNew(false);setNewCustomer("")};
 const addItem=async p=>{if(!tab)return;await request(`/comandas/${tab.id}/items`,{method:"POST",body:JSON.stringify({product_id:p.id,qty:+qty,note})});setQty(1);setNote("")};
 const cancelItem=async i=>{if(confirm(`Cancelar ${i.qty}x ${i.product_name}? O estoque será devolvido.`))await request(`/items/${i.id}`,{method:"DELETE"})};
 const duplicateItem=async i=>{await request(`/items/${i.id}/duplicate`,{method:"POST",body:"{}"})};
 const beginEdit=i=>{setEditingItem(i);setEditQty(i.qty);setEditNote(i.note||"")};
 const saveEdit=async()=>{await request(`/items/${editingItem.id}`,{method:"PUT",body:JSON.stringify({qty:+editQty,note:editNote})});setEditingItem(null)};
 const markDelivered=async i=>{await request(`/production/${i.id}/delivered`,{method:"POST",body:"{}"})};
 const closeTab=async()=>{if(!tab)return;if(confirm(`Fechar a comanda de ${tab.customer_name} em ${payment}?`)){await request(`/comandas/${tab.id}/close`,{method:"POST",body:JSON.stringify({payment_method:payment})});close()}};
 const closeWholeTable=async()=>{if(confirm(`Fechar TODAS as comandas de ${table.name} em ${payment}?`)){await request(`/tables/${table.id}/close`,{method:"POST",body:JSON.stringify({payment_method:payment})});close()}};
 const transferTable=async()=>{if(!targetTable)return;await request(`/tables/${table.id}/transfer`,{method:"POST",body:JSON.stringify({target_name:targetTable})});setShowTransfer(false);close()};
 const doTransferItem=async()=>{if(!transferItem||!targetComanda)return;await request(`/items/${transferItem.id}/transfer`,{method:"POST",body:JSON.stringify({target_comanda_id:+targetComanda})});setTransferItem(null);setTargetComanda("")};
 const doTransferComanda=async()=>{if(!tab||!targetTable)return;await request(`/comandas/${tab.id}/transfer`,{method:"POST",body:JSON.stringify({target_table_name:targetTable})});setTransferComandaOpen(false);close()};
 const subtotal=Number(tab?.total||0),service=Math.max(0,subtotal*Number(servicePercent||0)/100),finalTotal=Math.max(0,subtotal+service-Number(discount||0));
 const updatePayment=(idx,key,value)=>setPayments(payments.map((p,i)=>i===idx?{...p,[key]:value}:p));
 const addPayment=()=>setPayments([...payments,{payment_method:"Dinheiro",amount:""}]);
 const closeAdvanced=async()=>{if(!tab)return;const list=mixed?payments:[{payment_method:payment,amount:finalTotal}];await request(`/comandas/${tab.id}/close-advanced`,{method:"POST",body:JSON.stringify({service_percent:+servicePercent,discount:+discount,payments:list.map(x=>({...x,amount:+x.amount}))})});close()};
 return <div className="modalBack"><div className="modal tableModal"><div className="modalHead"><div><h2>{table.name}</h2><p>{money(table.total)} em aberto</p></div><div className="tableHeadActions"><button className="secondary compact" onClick={()=>setShowTransfer(true)}>Transferir mesa</button><button className="iconBtn" onClick={close}>×</button></div></div>
  <div className="workspace">
   <section className="tabsPane"><div className="sectionHead"><h3>Comandas</h3><button onClick={()=>setShowNew(true)}>+ Nova</button></div><div className="tabsList">{(table.comandas||[]).map(c=><button key={c.id} className={`tabCard ${tab?.id===c.id?"selected":""} ${c.status}`} onClick={()=>setTab(c)}><span>{c.customer_name||c.name}</span><small>{c.status==="open"?"Aberta":"Fechada"}</small><b>{money(c.total)}</b></button>)}</div></section>
   <section className="orderPane">{tab?<><div className="orderHeader"><div><span>Cliente</span><h3>{tab.customer_name||tab.name}</h3></div><div><span>Total</span><strong>{money(tab.total)}</strong></div></div>{tab.status==="open"&&<><div className="quickAdd"><input placeholder="Buscar produto" value={search} onChange={e=>setSearch(e.target.value)}/><input className="qty" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><input placeholder="Observação: bem passado, sem sal..." value={note} onChange={e=>setNote(e.target.value)}/></div><div className="menuProducts">{shown.map(p=><button key={p.id} onClick={()=>addItem(p)}><span>{p.name}</span><small>{p.sector}</small><b>{money(p.price)}</b></button>)}</div></>}
   <div className="orderItems">{(tab.items||[]).length===0?<div className="emptyState">Nenhum item nesta comanda.</div>:(tab.items||[]).map(i=>{const st=statusInfo[i.status]||statusInfo.waiting;return <div className={`orderItem professional ${i.status}`} key={i.id}><div className="itemMain"><div className="itemTitle"><b>{i.qty}x {i.product_name}</b><span className={`statusBadge ${i.status}`}>{st.icon} {st.label}</span></div><small>{i.sector}{i.note?` • ${i.note}`:""}</small><div className="itemActions">{tab.status==="open"&&!i.paid&&<><button className="smallBtn" onClick={()=>beginEdit(i)}>Editar</button><button className="smallBtn" onClick={()=>duplicateItem(i)}>Duplicar</button><button className="smallBtn" onClick={()=>{setTransferItem(i);setTargetComanda("")}}>Transferir</button>{i.status==="ready"&&<button className="smallBtn success" onClick={()=>markDelivered(i)}>Entregue</button>}<button className="smallBtn dangerText" onClick={()=>cancelItem(i)}>Cancelar</button></>}</div></div><strong>{money(i.qty*i.unit_price)}</strong></div>})}</div>
   {tab.status==="open"&&<div className="checkout proCheckout"><div className="checkoutSummary"><label>Serviço %<input type="number" min="0" value={servicePercent} onChange={e=>setServicePercent(e.target.value)}/></label><label>Desconto R$<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Serviço</span><b>{money(service)}</b></div><div className="checkoutTotal"><span>Total</span><strong>{money(finalTotal)}</strong></div></div><label className="mixedToggle"><input type="checkbox" checked={mixed} onChange={e=>{setMixed(e.target.checked);setPayments([{payment_method:"Pix",amount:finalTotal}])}}/> Pagamento misto</label>{!mixed?<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Pix</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Vale</option></select>:<div className="mixedPayments">{payments.map((p,idx)=><div key={idx}><select value={p.payment_method} onChange={e=>updatePayment(idx,"payment_method",e.target.value)}><option>Pix</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Vale</option></select><input type="number" step="0.01" value={p.amount} onChange={e=>updatePayment(idx,"amount",e.target.value)} placeholder="Valor"/>{payments.length>1&&<button className="dangerMini" onClick={()=>setPayments(payments.filter((_,i)=>i!==idx))}>×</button>}</div>)}<button className="secondary compact" onClick={addPayment}>+ Forma de pagamento</button><small>Somado: {money(payments.reduce((a,p)=>a+(+p.amount||0),0))}</small></div>}<button onClick={closeAdvanced}>Fechar comanda — {money(finalTotal)}</button><button className="secondary" onClick={()=>{setTransferComandaOpen(true);setTargetTable("")}}>Transferir comanda</button><button className="closeAll" onClick={closeWholeTable}>Fechar mesa inteira — {money(table.total)}</button></div>}</>:<div className="emptyState">Crie uma comanda para começar.</div>}</section>
  </div>
  {showNew&&<div className="innerModal"><h3>Nova comanda</h3><input autoFocus placeholder="Nome do cliente" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addComanda()}/><div className="modalActions"><button className="secondary" onClick={()=>setShowNew(false)}>Cancelar</button><button onClick={addComanda}>Criar comanda</button></div></div>}
  {editingItem&&<div className="innerModal"><h3>Editar item</h3><p>{editingItem.product_name}</p><div className="formGrid"><label>Quantidade<input type="number" min="1" value={editQty} onChange={e=>setEditQty(e.target.value)}/></label><label className="full">Observação<input autoFocus value={editNote} onChange={e=>setEditNote(e.target.value)} placeholder="Ex.: bem passado"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setEditingItem(null)}>Cancelar</button><button onClick={saveEdit}>Salvar alteração</button></div></div>}
  {showTransfer&&<div className="innerModal"><h3>Transferir {table.name}</h3><p>Todos os clientes, comandas e pedidos serão movidos juntos.</p><select autoFocus value={targetTable} onChange={e=>setTargetTable(e.target.value)}><option value="">Escolha a mesa de destino</option>{Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`).concat(Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)).filter(n=>n!==table.name).map(n=><option key={n}>{n}</option>)}</select><div className="modalActions"><button className="secondary" onClick={()=>setShowTransfer(false)}>Cancelar</button><button onClick={transferTable}>Confirmar transferência</button></div></div>}
  {transferItem&&<div className="innerModal"><h3>Transferir item</h3><p>{transferItem.qty}x {transferItem.product_name}</p><select value={targetComanda} onChange={e=>setTargetComanda(e.target.value)}><option value="">Escolha a comanda</option>{(table.comandas||[]).filter(c=>c.status==="open"&&c.id!==tab?.id).map(c=><option value={c.id} key={c.id}>{c.customer_name||c.name}</option>)}</select><div className="modalActions"><button className="secondary" onClick={()=>setTransferItem(null)}>Cancelar</button><button onClick={doTransferItem}>Transferir item</button></div></div>}
  {transferComandaOpen&&<div className="innerModal"><h3>Transferir comanda</h3><p>Mover a comanda de <b>{tab?.customer_name}</b> para outra mesa ou bistrô.</p><select value={targetTable} onChange={e=>setTargetTable(e.target.value)}><option value="">Escolha o destino</option>{Array.from({length:20},(_,i)=>`Mesa ${String(i+1).padStart(2,"0")}`).concat(Array.from({length:4},(_,i)=>`Bistrô ${String(i+1).padStart(2,"0")}`)).filter(n=>n!==table.name).map(n=><option key={n}>{n}</option>)}</select><div className="modalActions"><button className="secondary" onClick={()=>setTransferComandaOpen(false)}>Cancelar</button><button onClick={doTransferComanda}>Transferir comanda</button></div></div>}
 </div></div>
}
function Production({items,printJobs,request}){
 const sectors=["Bar","Churrasqueira","Cozinha","Fritadeira"];
 const[sector,setSector]=useState("Todos"),[tick,setTick]=useState(Date.now());
 useEffect(()=>{const x=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(x)},[]);
 const visible=sector==="Todos"?items:items.filter(i=>i.sector===sector);
 const nextStatus=i=>i.status==="waiting"?"preparing":i.status==="preparing"?"ready":"delivered";
 const nextLabel=i=>i.status==="waiting"?"Iniciar preparo":i.status==="preparing"?"Marcar pronto":"Marcar entregue";
 const elapsed=i=>{const sec=Math.max(0,Math.floor((tick-new Date(i.created_at).getTime())/1000));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`};
 const pendingFor=s=>printJobs.filter(j=>s==="Todos"||j.sector===s);
 const printSector=async s=>{
   const jobs=pendingFor(s);if(!jobs.length)return alert("Não há pedidos pendentes para imprimir.");
   const grouped={};jobs.forEach(j=>{const k=`${j.table_name} — ${j.customer_name}`;(grouped[k]??=[]).push(j)});
   const body=Object.entries(grouped).map(([title,rows])=>`<section><h2>${title}</h2><p>${new Date().toLocaleString("pt-BR")}</p>${rows.map(r=>`<div class="item"><b>${r.qty}x ${r.product_name}</b>${r.note?`<small>OBS: ${r.note}</small>`:""}</div>`).join("")}</section>`).join("");
   const w=window.open("","_blank","width=420,height=700");
   if(!w)return alert("O navegador bloqueou a janela de impressão.");
   w.document.write(`<html><head><title>Produção ${s}</title><style>body{font-family:monospace;padding:12px;color:#000}h1{text-align:center;border-bottom:2px dashed #000;padding-bottom:10px}section{border-bottom:2px dashed #000;padding:10px 0}h2{margin:0 0 4px}.item{font-size:17px;margin:10px 0}.item small{display:block;font-size:13px;margin-top:3px}</style></head><body><h1>REI'SPETOS — ${s}</h1>${body}</body></html>`);
   w.document.close();w.focus();setTimeout(()=>w.print(),250);
   for(const j of jobs)await request(`/print-jobs/${j.id}/printed`,{method:"POST",body:"{}"});
 };
 const reprint=async i=>{await request(`/production/${i.id}/reprint`,{method:"POST",body:"{}"})};
 return <div className="kds">
  <div className="productionSummary"><span><b>{items.filter(i=>i.status==="waiting").length}</b> aguardando</span><span><b>{items.filter(i=>i.status==="preparing").length}</b> em preparo</span><span><b>{items.filter(i=>i.status==="ready").length}</b> prontos</span><span><b>{printJobs.length}</b> para imprimir</span></div>
  <div className="kdsToolbar"><div className="filters">{["Todos",...sectors].map(s=><button key={s} className={sector===s?"active":""} onClick={()=>setSector(s)}>{s}</button>)}</div><button className="printBtn" onClick={()=>printSector(sector)}>🖨 Imprimir pendentes ({pendingFor(sector).length})</button></div>
  <div className="grid2 productionGrid">{sectors.filter(s=>sector==="Todos"||s===sector).map(s=><div className="panel productionPanel" key={s}><div className="productionHead"><h3>{s}</h3><span>{visible.filter(i=>i.sector===s).length} pedido(s)</span></div>{visible.filter(i=>i.sector===s).length===0?<div className="emptyState">Nenhum pedido neste setor.</div>:visible.filter(i=>i.sector===s).map(i=>{const st=statusInfo[i.status]||statusInfo.waiting;const mins=Math.floor((tick-new Date(i.created_at).getTime())/60000);return <div className={`productionTicket ${i.status} ${mins>=15?"urgent":""}`} key={i.id}><div className="ticketTop"><div><strong>{i.table_name}</strong><small>{i.customer_name}</small></div><div className="ticketMeta"><span className={`timer ${mins>=15?"late":""}`}>⏱ {elapsed(i)}</span><span className={`statusBadge ${i.status}`}>{st.icon} {st.label}</span></div></div><h4>{i.qty}x {i.product_name}</h4>{i.note&&<p className="ticketNote">Obs.: {i.note}</p>}<div className="ticketActions"><button onClick={()=>request(`/production/${i.id}/${nextStatus(i)}`,{method:"POST",body:"{}"})}>{nextLabel(i)}</button><button className="secondary" onClick={()=>reprint(i)}>🖨 Reimprimir</button></div></div>})}</div>)}</div>
  <p className="printNotice">A impressão abre a caixa de diálogo do navegador. Impressão silenciosa automática exige um conector local da impressora, que será configurado em uma etapa posterior.</p>
 </div>
}
function Cash({data,request}){
 const[opening,setOpening]=useState(0),[move,setMove]=useState({movement_type:"supply",amount:0,note:""}),[tab,setTab]=useState("today"),[history,setHistory]=useState([]),[counts,setCounts]=useState({}),[closeNote,setCloseNote]=useState(""),[detail,setDetail]=useState(null);
 const labels={supply:"Suprimento",withdrawal:"Sangria",expense:"Despesa"};
 const methods=["Dinheiro","Pix","Débito","Crédito","Vale"];
 useEffect(()=>{if(tab==="history")request("/cash/history?limit=50",{method:"GET"}).then(setHistory)},[tab]);
 useEffect(()=>{if(data.open){const c={};methods.forEach(m=>c[m]=m==="Dinheiro"?Number(data.cash_expected||0):Number(data.payment_totals?.[m]||0));setCounts(c)}},[data.open,data.session?.id]);
 const openCash=async()=>{await request("/cash/open",{method:"POST",body:JSON.stringify({opening_amount:+opening})});setOpening(0)};
 const addMove=async()=>{await request("/cash/movement",{method:"POST",body:JSON.stringify({...move,amount:+move.amount})});setMove({movement_type:"supply",amount:0,note:""})};
 const closeCash=async()=>{const expected=methods.reduce((a,m)=>a+(m==="Dinheiro"?Number(data.cash_expected||0):Number(data.payment_totals?.[m]||0)),0),counted=methods.reduce((a,m)=>a+Number(counts[m]||0),0);if(confirm(`Fechar caixa?\nEsperado: ${money(expected)}\nConferido: ${money(counted)}\nDiferença: ${money(counted-expected)}`)){await request("/cash/close-pro",{method:"POST",body:JSON.stringify({counts, note:closeNote})});setCloseNote("");setTab("history")}};
 const openDetail=async id=>setDetail(await request(`/cash/session/${id}`,{method:"GET"}));
 const paymentTotals=data.payment_totals||{};
 const expectedTotal=methods.reduce((a,m)=>a+(m==="Dinheiro"?Number(data.cash_expected||0):Number(paymentTotals[m]||0)),0);
 const countedTotal=methods.reduce((a,m)=>a+Number(counts[m]||0),0);
 if(!data.open)return <div className="cashProPage">
  <div className="cashHero closed"><div><span>Controle de caixa</span><h2>Caixa fechado</h2><p>Abra o expediente informando o fundo inicial para troco.</p></div><div className="cashOpenForm"><label>Fundo inicial<input type="number" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)}/></label><button onClick={openCash}>Abrir caixa</button></div></div>
  <div className="cashTabs"><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Histórico de caixas</button></div>
  {tab==="history"&&<CashHistory rows={history} openDetail={openDetail}/>}
  {detail&&<CashDetail data={detail} close={()=>setDetail(null)}/>}
 </div>;
 return <div className="cashProPage">
  <div className="cashTop"><div><span>Expediente aberto</span><h2>Caixa #{data.session?.id}</h2><p>Aberto por {data.session?.opened_by}</p></div><div className="cashClock"><span>Vendas</span><b>{data.sales_count||0}</b><small>Ticket médio {money(data.ticket_average)}</small></div></div>
  <div className="cashTabs"><button className={tab==="today"?"active":""} onClick={()=>setTab("today")}>Resumo</button><button className={tab==="moves"?"active":""} onClick={()=>setTab("moves")}>Movimentações</button><button className={tab==="close"?"active":""} onClick={()=>setTab("close")}>Conferência e fechamento</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Histórico</button></div>
  {tab==="today"&&<><div className="cards cashProCards"><div className="card"><span>Fundo inicial</span><b>{money(data.session?.opening_amount)}</b></div><div className="card"><span>Vendas</span><b>{money(data.sales_total)}</b></div><div className="card"><span>Suprimentos</span><b className="greenText">{money(data.supplies)}</b></div><div className="card"><span>Sangrias e despesas</span><b className="redText">{money(data.withdrawals)}</b></div><div className="card highlight"><span>Dinheiro esperado</span><b>{money(data.cash_expected)}</b></div></div>
   <section className="panel"><div className="sectionHead"><div><h3>Vendas por forma de pagamento</h3><p>Valores recebidos desde a abertura do caixa.</p></div></div><div className="paymentCards">{methods.map(m=><div key={m}><span>{m}</span><b>{money(paymentTotals[m]||0)}</b></div>)}</div></section>
   <section className="panel"><div className="sectionHead"><div><h3>Últimas vendas</h3><p>Vendas registradas no expediente.</p></div><span>{(data.sales||[]).length} registro(s)</span></div><div className="saleList">{(data.sales||[]).length===0?<div className="emptyState">Nenhuma venda registrada.</div>:(data.sales||[]).slice(0,20).map(s=><div className="saleRow" key={s.id}><div><b>{s.reference||s.origin}</b><small>{s.payment_method} • Venda #{s.id}</small></div><strong>{money(s.total)}</strong></div>)}</div></section></>}
  {tab==="moves"&&<div className="grid2 cashGrid"><section className="panel"><div className="sectionHead"><div><h3>Nova movimentação</h3><p>Registre suprimentos, sangrias e despesas pagas.</p></div></div><div className="formGrid"><label>Tipo<select value={move.movement_type} onChange={e=>setMove({...move,movement_type:e.target.value})}><option value="supply">Suprimento</option><option value="withdrawal">Sangria</option><option value="expense">Despesa paga</option></select></label><label>Valor<input type="number" step="0.01" value={move.amount} onChange={e=>setMove({...move,amount:e.target.value})}/></label><label className="full">Motivo<input value={move.note} onChange={e=>setMove({...move,note:e.target.value})} placeholder="Ex.: retirada para o cofre"/></label></div><button onClick={addMove}>Registrar movimentação</button></section><section className="panel"><div className="sectionHead"><h3>Movimentações do expediente</h3><span>{(data.movements||[]).length}</span></div><div className="cashMovements">{(data.movements||[]).length===0?<div className="emptyState">Nenhuma movimentação.</div>:(data.movements||[]).map(x=><div className={`cashMovement ${x.movement_type}`} key={x.id}><div><b>{labels[x.movement_type]||x.movement_type}</b><small>{x.note||"Sem observação"} • {x.username}</small></div><strong>{x.movement_type==="supply"?"+":"−"} {money(x.amount)}</strong></div>)}</div></section></div>}
  {tab==="close"&&<section className="panel closePro"><div className="sectionHead"><div><h3>Conferência do caixa</h3><p>Informe quanto foi conferido em cada forma de pagamento.</p></div></div><div className="countTable"><div className="countHead"><span>Forma</span><span>Esperado</span><span>Conferido</span><span>Diferença</span></div>{methods.map(m=>{const exp=m==="Dinheiro"?Number(data.cash_expected||0):Number(paymentTotals[m]||0),cnt=Number(counts[m]||0),diff=cnt-exp;return <div className="countRow" key={m}><b>{m}</b><span>{money(exp)}</span><input type="number" step="0.01" value={counts[m]??0} onChange={e=>setCounts({...counts,[m]:e.target.value})}/><strong className={diff===0?"":diff>0?"greenText":"redText"}>{money(diff)}</strong></div>})}</div><div className="closeTotals"><div><span>Total esperado</span><b>{money(expectedTotal)}</b></div><div><span>Total conferido</span><b>{money(countedTotal)}</b></div><div><span>Diferença geral</span><strong className={countedTotal-expectedTotal===0?"":countedTotal>expectedTotal?"greenText":"redText"}>{money(countedTotal-expectedTotal)}</strong></div></div><textarea value={closeNote} onChange={e=>setCloseNote(e.target.value)} placeholder="Observação do fechamento (opcional)"/><button className="danger closeCashButton" onClick={closeCash}>Confirmar e fechar caixa</button></section>}
  {tab==="history"&&<CashHistory rows={history} openDetail={openDetail}/>}
  {detail&&<CashDetail data={detail} close={()=>setDetail(null)}/>}
 </div>
}
function CashHistory({rows,openDetail}){
 return <section className="panel"><div className="sectionHead"><div><h3>Histórico de caixas</h3><p>Conferências e diferenças dos últimos expedientes.</p></div><span>{rows.length} caixa(s)</span></div><div className="cashHistoryList">{rows.length===0?<div className="emptyState">Nenhum caixa fechado.</div>:rows.map(x=><button className="cashHistoryRow" key={x.id} onClick={()=>openDetail(x.id)}><div><b>Caixa #{x.id}</b><small>{x.opened_by} • {x.status==="open"?"Aberto":"Fechado"}</small></div><span>{x.sales_count} venda(s)<small>{money(x.sales_total)}</small></span><span>Esperado<small>{money(x.expected_amount)}</small></span><span>Diferença<strong className={Number(x.difference||0)===0?"":Number(x.difference)>0?"greenText":"redText"}>{money(x.difference)}</strong></span></button>)}</div></section>
}
function CashDetail({data,close}){
 const s=data.session||{};
 return <div className="modalBack"><div className="innerModal cashDetailModal"><div className="sectionHead"><div><h3>Caixa #{s.id}</h3><p>Operador: {s.opened_by}</p></div><button className="iconBtn" onClick={close}>×</button></div><div className="cards detailCards"><div className="card"><span>Esperado</span><b>{money(s.expected_amount)}</b></div><div className="card"><span>Conferido</span><b>{money(s.counted_amount)}</b></div><div className="card"><span>Diferença</span><b>{money(s.difference)}</b></div></div><h4>Conferência por forma</h4><div className="countTable">{(data.counts||[]).map(x=><div className="countRow" key={x.id}><b>{x.payment_method}</b><span>{money(x.expected_amount)}</span><span>{money(x.counted_amount)}</span><strong>{money(x.difference)}</strong></div>)}</div><h4>Movimentações</h4><div className="cashMovements">{(data.movements||[]).map(x=><div className={`cashMovement ${x.movement_type}`} key={x.id}><div><b>{x.movement_type}</b><small>{x.note}</small></div><strong>{money(x.amount)}</strong></div>)}</div></div></div>
}

function Reports({request}){
 const[days,setDays]=useState(30),[report,setReport]=useState(null),[loading,setLoading]=useState(false);
 const load=async d=>{setLoading(true);try{setReport(await request(`/reports/summary?days=${d}`,{method:"GET"}))}finally{setLoading(false)}};
 useEffect(()=>{load(days)},[]);
 const change=d=>{setDays(d);load(d)};
 const maxDaily=Math.max(1,...(report?.daily||[]).map(x=>x.value));
 if(!report)return <div className="panel">{loading?"Carregando relatório...":"Sem dados disponíveis."}</div>;
 return <div className="reportsPage">
  <div className="reportToolbar"><div><h2>Visão gerencial</h2><p>Vendas, lucro, ticket médio e produtos mais vendidos.</p></div><div className="periodButtons">{[7,30,90].map(d=><button key={d} className={days===d?"active":""} onClick={()=>change(d)}>{d} dias</button>)}</div></div>
  <div className="cards reportCards">
   <div className="card"><span>Faturamento</span><b>{money(report.revenue)}</b></div>
   <div className="card"><span>Lucro estimado</span><b>{money(report.profit)}</b><small>Margem {Number(report.margin||0).toFixed(1)}%</small></div>
   <div className="card"><span>Ticket médio</span><b>{money(report.ticket_average)}</b><small>{report.sales_count} venda(s)</small></div>
   <div className="card"><span>CMV</span><b>{money(report.cost)}</b><small>Custos dos produtos</small></div>
   <div className="card"><span>Despesas pagas</span><b>{money(report.expenses)}</b></div>
  </div>
  <div className="grid2 reportGrid">
   <section className="panel"><div className="sectionHead"><div><h3>Faturamento diário</h3><p>Movimento dos últimos {report.period_days} dias.</p></div></div><div className="dailyChart">{(report.daily||[]).length===0?<div className="emptyState">Ainda não existem vendas neste período.</div>:(report.daily||[]).map(x=><div className="dailyBar" key={x.date} title={`${x.date}: ${money(x.value)}`}><div className="barValue">{money(x.value)}</div><div className="barTrack"><span style={{height:`${Math.max(5,x.value/maxDaily*100)}%`}}></span></div><small>{x.date.slice(5)}</small></div>)}</div></section>
   <section className="panel"><div className="sectionHead"><div><h3>Formas de pagamento</h3><p>Participação no faturamento.</p></div></div><div className="paymentReport">{(report.payments||[]).length===0?<div className="emptyState">Nenhum pagamento registrado.</div>:(report.payments||[]).map(x=>{const pct=report.revenue?x.value/report.revenue*100:0;return <div className="paymentRow" key={x.name}><div><b>{x.name}</b><span>{money(x.value)}</span></div><div className="paymentTrack"><span style={{width:`${pct}%`}}></span></div><small>{pct.toFixed(1)}%</small></div>})}</div></section>
  </div>
  <section className="panel"><div className="sectionHead"><div><h3>Produtos mais vendidos</h3><p>Ranking por quantidade no período.</p></div></div><div className="reportTable"><div className="reportTableHead"><span>Produto</span><span>Quantidade</span><span>Faturamento</span><span>Lucro estimado</span></div>{(report.top_products||[]).length===0?<div className="emptyState">Nenhum produto vendido neste período.</div>:(report.top_products||[]).map((x,i)=><div className="reportTableRow" key={x.name}><span><b className="rank">#{i+1}</b>{x.name}</span><span>{x.qty}</span><span>{money(x.revenue)}</span><span className="positive">{money(x.profit)}</span></div>)}</div></section>
 </div>
}

function Customers({items,request}){
 const[search,setSearch]=useState(""),[form,setForm]=useState({name:"",phone:""}),[editing,setEditing]=useState(null),[points,setPoints]=useState(null),[pointForm,setPointForm]=useState({delta:10,reason:"Fidelidade"});
 const filtered=items.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(search.toLowerCase()));
 const save=async()=>{if(editing){await request(`/customers/${editing.id}`,{method:"PUT",body:JSON.stringify(form)})}else{await request("/customers",{method:"POST",body:JSON.stringify(form)})}setForm({name:"",phone:""});setEditing(null)};
 const edit=c=>{setEditing(c);setForm({name:c.name,phone:c.phone})};
 const cancel=()=>{setEditing(null);setForm({name:"",phone:""})};
 const applyPoints=async()=>{await request(`/customers/${points.id}/points`,{method:"POST",body:JSON.stringify({delta:+pointForm.delta,reason:pointForm.reason})});setPoints(null);setPointForm({delta:10,reason:"Fidelidade"})};
 const remove=async c=>{if(confirm(`Excluir o cliente ${c.name}?`))await request(`/customers/${c.id}`,{method:"DELETE"})};
 const phoneLink=p=>`https://wa.me/55${String(p||"").replace(/\D/g,"")}`;
 const totalPoints=items.reduce((a,c)=>a+(c.points||0),0),totalSpent=items.reduce((a,c)=>a+(c.total_spent||0),0),vip=items.filter(c=>(c.points||0)>=100).length;
 return <div className="crmPage">
  <div className="cards crmCards"><div className="card"><span>Clientes cadastrados</span><b>{items.length}</b></div><div className="card"><span>Pontos distribuídos</span><b>{totalPoints}</b></div><div className="card"><span>Clientes VIP</span><b>{vip}</b><small>100 pontos ou mais</small></div><div className="card"><span>Consumo registrado</span><b>{money(totalSpent)}</b></div></div>
  <section className="panel crmForm"><div className="sectionHead"><div><h3>{editing?"Editar cliente":"Novo cliente"}</h3><p>Cadastre o contato para fidelização e atendimento pelo WhatsApp.</p></div></div><div className="crmFormGrid"><input placeholder="Nome completo" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Telefone com DDD" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><button onClick={save}>{editing?"Salvar alteração":"Cadastrar cliente"}</button>{editing&&<button className="secondary" onClick={cancel}>Cancelar</button>}</div></section>
  <div className="crmToolbar"><input placeholder="Buscar cliente por nome ou telefone..." value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} cliente(s)</span></div>
  <div className="crmGrid">{filtered.length===0?<div className="panel emptyState">Nenhum cliente encontrado.</div>:filtered.map(c=><article className="customerCard" key={c.id}><div className="customerTop"><div className="customerAvatar">{c.name?.slice(0,1).toUpperCase()}</div><div><h3>{c.name}</h3><a href={phoneLink(c.phone)} target="_blank" rel="noreferrer">{c.phone}</a></div><span className={(c.points||0)>=100?"vipBadge":"pointsBadge"}>{(c.points||0)>=100?"VIP":`${c.points||0} pts`}</span></div><div className="customerStats"><div><span>Visitas</span><b>{c.visits||0}</b></div><div><span>Total gasto</span><b>{money(c.total_spent)}</b></div><div><span>Pontos</span><b>{c.points||0}</b></div></div><div className="customerActions"><button onClick={()=>setPoints(c)}>+ Pontos</button><button className="secondary" onClick={()=>edit(c)}>Editar</button><a className="waButton" href={phoneLink(c.phone)} target="_blank" rel="noreferrer">WhatsApp</a><button className="dangerMini" onClick={()=>remove(c)}>Excluir</button></div></article>)}</div>
  {points&&<div className="modalBack"><div className="innerModal pointsModal"><h3>Ajustar pontos</h3><p>{points.name} possui <b>{points.points||0} pontos</b>.</p><div className="formGrid"><label>Quantidade<input type="number" value={pointForm.delta} onChange={e=>setPointForm({...pointForm,delta:e.target.value})}/></label><label>Motivo<input value={pointForm.reason} onChange={e=>setPointForm({...pointForm,reason:e.target.value})} placeholder="Ex.: compra, prêmio, ajuste"/></label></div><div className="quickPoints"><button onClick={()=>setPointForm({...pointForm,delta:10})}>+10</button><button onClick={()=>setPointForm({...pointForm,delta:25})}>+25</button><button onClick={()=>setPointForm({...pointForm,delta:50})}>+50</button><button className="secondary" onClick={()=>setPointForm({...pointForm,delta:-10})}>−10</button></div><div className="modalActions"><button className="secondary" onClick={()=>setPoints(null)}>Cancelar</button><button onClick={applyPoints}>Confirmar ajuste</button></div></div></div>}
 </div>
}
function Reservations({items,request}){const[f,setF]=useState({customer_name:"",phone:"",date:"",time:"",people:2,table_name:"Mesa 01"});return <><div className="panel formGrid"><input placeholder="Cliente" onChange={e=>setF({...f,customer_name:e.target.value})}/><input placeholder="Telefone" onChange={e=>setF({...f,phone:e.target.value})}/><input type="date" onChange={e=>setF({...f,date:e.target.value})}/><input type="time" onChange={e=>setF({...f,time:e.target.value})}/><button onClick={()=>request("/reservations",{method:"POST",body:JSON.stringify(f)})}>Reservar</button></div><div className="panel">{items.map(r=><div className="item" key={r.id}><b>{r.customer_name}</b><div>{r.date} {r.time} — {r.people} pessoas</div></div>)}</div></>}

function Finance({request}){
 const[summary,setSummary]=useState(null),[entries,setEntries]=useState([]),[filter,setFilter]=useState("all"),[type,setType]=useState("all"),[showForm,setShowForm]=useState(false),[form,setForm]=useState({entry_type:"expense",description:"",category:"Fornecedores",supplier:"",amount:0,due_date:"",payment_method:"Pix",status:"pending",recurrence:"none",notes:""});
 const load=async()=>{setSummary(await request("/finance/summary",{method:"GET"}));setEntries(await request(`/finance/entries?status=${filter}&entry_type=${type}`,{method:"GET"}))};
 useEffect(()=>{load()},[filter,type]);
 const save=async()=>{await request("/finance/entries",{method:"POST",body:JSON.stringify({...form,amount:+form.amount})});setShowForm(false);setForm({entry_type:"expense",description:"",category:"Fornecedores",supplier:"",amount:0,due_date:"",payment_method:"Pix",status:"pending",recurrence:"none",notes:""});await load()};
 const setStatus=async(x,status)=>{await request(`/finance/entries/${x.id}/status`,{method:"PUT",body:JSON.stringify({status,payment_method:x.payment_method||"Pix"})});await load()};
 const remove=async x=>{if(confirm(`Excluir o lançamento "${x.description}"?`)){await request(`/finance/entries/${x.id}`,{method:"DELETE"});await load()}};
 const today=new Date().toISOString().slice(0,10);
 const statusLabel={pending:"Pendente",paid:"Pago",cancelled:"Cancelado"};
 const recurrenceLabel={none:"Único",weekly:"Semanal",monthly:"Mensal",yearly:"Anual"};
 if(!summary)return <div className="panel">Carregando financeiro...</div>;
 return <div className="financePage">
  <div className="financeHero"><div><span>Controle financeiro</span><h2>Visão completa do dinheiro</h2><p>Contas a pagar, receber, vencimentos e resultado realizado.</p></div><button onClick={()=>setShowForm(true)}>+ Novo lançamento</button></div>
  <div className="cards financeCards"><div className="card"><span>A receber</span><b className="greenText">{money(summary.receivable)}</b></div><div className="card"><span>A pagar</span><b className="redText">{money(summary.payable)}</b></div><div className="card"><span>Saldo realizado</span><b>{money(summary.balance)}</b></div><div className="card"><span>Saldo projetado</span><b>{money(summary.projected_balance)}</b></div><div className="card"><span>Vencidos</span><b className={summary.overdue_count?"redText":""}>{summary.overdue_count}</b></div></div>
  <div className="financeToolbar"><div className="filters">{[["all","Todos"],["pending","Pendentes"],["paid","Pagos"],["cancelled","Cancelados"]].map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Entradas e saídas</option><option value="income">Somente entradas</option><option value="expense">Somente despesas</option></select></div>
  <div className="financeLayout">
   <section className="panel"><div className="sectionHead"><div><h3>Lançamentos</h3><p>{entries.length} registro(s) no filtro atual.</p></div></div><div className="financeList">{entries.length===0?<div className="emptyState">Nenhum lançamento encontrado.</div>:entries.map(x=>{const overdue=x.status==="pending"&&x.due_date&&x.due_date<today;return <article className={`financeRow ${x.entry_type} ${overdue?"overdue":""}`} key={x.id}><div className="financeType">{x.entry_type==="income"?"↗":"↘"}</div><div className="financeInfo"><div><h4>{x.description}</h4><span className={`financeStatus ${x.status}`}>{overdue?"Vencido":statusLabel[x.status]}</span></div><p>{x.supplier||x.category} • {x.category}</p><small>Vencimento: {x.due_date||"Não informado"} • {recurrenceLabel[x.recurrence]||"Único"}{x.payment_method?` • ${x.payment_method}`:""}</small></div><strong className={x.entry_type==="income"?"greenText":"redText"}>{x.entry_type==="income"?"+":"−"} {money(x.amount)}</strong><div className="financeActions">{x.status==="pending"&&<button onClick={()=>setStatus(x,"paid")}>Marcar pago</button>}{x.status==="paid"&&<button className="secondary" onClick={()=>setStatus(x,"pending")}>Reabrir</button>}<button className="dangerMini" onClick={()=>remove(x)}>Excluir</button></div></article>})}</div></section>
   <aside className="panel categoryPanel"><div className="sectionHead"><div><h3>Despesas por categoria</h3><p>Valores já pagos.</p></div></div>{(summary.categories||[]).length===0?<div className="emptyState">Sem despesas pagas.</div>:(summary.categories||[]).map(x=>{const max=Math.max(...summary.categories.map(c=>c.value),1);return <div className="categoryFinance" key={x.name}><div><b>{x.name}</b><span>{money(x.value)}</span></div><div><span style={{width:`${x.value/max*100}%`}}></span></div></div>})}</aside>
  </div>
  {showForm&&<div className="modalBack"><div className="innerModal financeModal"><div className="sectionHead"><div><h3>Novo lançamento</h3><p>Registre conta, fornecedor, vencimento e forma de pagamento.</p></div></div><div className="formGrid"><label>Tipo<select value={form.entry_type} onChange={e=>setForm({...form,entry_type:e.target.value})}><option value="expense">Despesa / saída</option><option value="income">Receita / entrada</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pendente</option><option value="paid">Pago/recebido</option></select></label><label className="full">Descrição<input autoFocus value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ex.: Compra de carvão"/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Fornecedores</option><option>Bebidas</option><option>Alimentos</option><option>Funcionários</option><option>Aluguel</option><option>Energia</option><option>Água</option><option>Internet</option><option>Manutenção</option><option>Impostos</option><option>Marketing</option><option>Outros</option></select></label><label>Fornecedor<input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})} placeholder="Nome do fornecedor"/></label><label>Valor<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Vencimento<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label>Pagamento<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option>Pix</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Boleto</option><option>Transferência</option></select></label><label>Recorrência<select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}><option value="none">Único</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label><label className="full">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Detalhes do lançamento"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setShowForm(false)}>Cancelar</button><button onClick={save}>Salvar lançamento</button></div></div></div>}
 </div>
}

function Expenses({items,request}){const[f,setF]=useState({description:"",category:"Outros",amount:0,status:"pending"});return <><div className="panel form"><input placeholder="Descrição" onChange={e=>setF({...f,description:e.target.value})}/><input type="number" placeholder="Valor" onChange={e=>setF({...f,amount:+e.target.value})}/><button onClick={()=>request("/expenses",{method:"POST",body:JSON.stringify(f)})}>Cadastrar</button></div><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.description}</b><div>{money(x.amount)} — {x.status}</div></div>)}</div></>}
const Audit=({items})=><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.action}</b><div>{x.username} — {x.detail}</div></div>)}</div>;

export default App;
